// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: job/apply.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "applies";

/** Enums */
export enum AppliedStatus {
  APPLIED_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  INTERVIEW = 2,
  CONFIRMED = 3,
  REJECTED = 4,
  SUCCESS = 5,
  UNRECOGNIZED = -1,
}

/** Message */
export interface Apply {
  id: string;
  jobPostId: string;
  userId: string;
  userInfoId?: string | undefined;
  isReviewed: boolean;
  status: AppliedStatus;
  appliedAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface ApplyResponse {
  success: boolean;
  message?: string | undefined;
}

export interface ListAppliesResponse {
  applies: Apply[];
  total: number;
  page: number;
  limit: number;
}

export interface DeleteApplyResponse {
  success: boolean;
  message: string;
}

export interface AllAppliesWithMetaResponse {
  data: Apply[];
  meta: PaginationMeta | undefined;
}

export interface SingleApplyResponse {
  message?: string | undefined;
  apply: Apply | undefined;
}

/**
 * ---------------------
 * CRUD Requests
 * ---------------------
 */
export interface ListAppliesRequest {
  page: number;
  limit: number;
  status?: AppliedStatus | undefined;
  userId?: string | undefined;
  jobPostId?: string | undefined;
  isReviewed?: boolean | undefined;
}

export interface GetApplyRequest {
  applyId: string;
}

export interface UpdateApplyRequest {
  applyId: string;
  isReviewed?: boolean | undefined;
  status?: AppliedStatus | undefined;
  userInfoId?: string | undefined;
}

export interface DeleteApplyRequest {
  applyId: string;
}

export interface GetAllAppliesRequest {
  basicQuery: BasicQuery | undefined;
}

export interface CreateApplyRequest {
  jobPostId: string;
  userId: string;
  userInfoId?: string | undefined;
  isReviewed?: boolean | undefined;
  status?: AppliedStatus | undefined;
}

export const APPLIES_PACKAGE_NAME = "applies";

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface ApplyServiceClient {
  createApply(request: CreateApplyRequest): Observable<ApplyResponse>;

  getApply(request: GetApplyRequest): Observable<SingleApplyResponse>;

  getAllApplies(request: GetAllAppliesRequest): Observable<AllAppliesWithMetaResponse>;

  updateApply(request: UpdateApplyRequest): Observable<ApplyResponse>;

  deleteApply(request: DeleteApplyRequest): Observable<DeleteApplyResponse>;

  listApplies(request: ListAppliesRequest): Observable<ListAppliesResponse>;
}

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface ApplyServiceController {
  createApply(request: CreateApplyRequest): Promise<ApplyResponse> | Observable<ApplyResponse> | ApplyResponse;

  getApply(
    request: GetApplyRequest,
  ): Promise<SingleApplyResponse> | Observable<SingleApplyResponse> | SingleApplyResponse;

  getAllApplies(
    request: GetAllAppliesRequest,
  ): Promise<AllAppliesWithMetaResponse> | Observable<AllAppliesWithMetaResponse> | AllAppliesWithMetaResponse;

  updateApply(request: UpdateApplyRequest): Promise<ApplyResponse> | Observable<ApplyResponse> | ApplyResponse;

  deleteApply(
    request: DeleteApplyRequest,
  ): Promise<DeleteApplyResponse> | Observable<DeleteApplyResponse> | DeleteApplyResponse;

  listApplies(
    request: ListAppliesRequest,
  ): Promise<ListAppliesResponse> | Observable<ListAppliesResponse> | ListAppliesResponse;
}

export function ApplyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createApply",
      "getApply",
      "getAllApplies",
      "updateApply",
      "deleteApply",
      "listApplies",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ApplyService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ApplyService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const APPLY_SERVICE_NAME = "ApplyService";
