// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: job/category.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "category";

/**
 * ---------------------
 * Category Messages
 * ---------------------
 */
export interface Category {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  parentCategoryId?: string | undefined;
  parent?: Category | undefined;
  children: Category[];
  createdAt: string;
  updatedAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface CategoryResponse {
  success: boolean;
  message?: string | undefined;
  category: Category | undefined;
}

export interface AllCategoriesWithMetaResponse {
  data: Category[];
  meta: PaginationMeta | undefined;
}

export interface DeleteCategoryResponse {
  success: boolean;
  message: string;
}

export interface ListCategoriesResponse {
  categories: Category[];
  total: number;
  page: number;
  limit: number;
}

/**
 * ---------------------
 * CRUD Requests
 * ---------------------
 */
export interface CreateCategoryRequest {
  name?: string | undefined;
  description?: string | undefined;
  parentCategoryId?: string | undefined;
}

export interface GetCategoryRequest {
  categoryId: string;
}

export interface GetAllCategoriesRequest {
  basicQuery: BasicQuery | undefined;
}

export interface UpdateCategoryRequest {
  categoryId: string;
  name?: string | undefined;
  description?: string | undefined;
  parentCategoryId?: string | undefined;
}

export interface DeleteCategoryRequest {
  categoryId: string;
}

export interface ListCategoriesRequest {
  page: number;
  limit: number;
  search?: string | undefined;
}

export const CATEGORY_PACKAGE_NAME = "category";

/**
 * ---------------------
 * Service Definition
 * ---------------------
 */

export interface CategoryServiceClient {
  createCategory(request: CreateCategoryRequest): Observable<CategoryResponse>;

  getCategory(request: GetCategoryRequest): Observable<CategoryResponse>;

  getAllCategories(request: GetAllCategoriesRequest): Observable<AllCategoriesWithMetaResponse>;

  updateCategory(request: UpdateCategoryRequest): Observable<CategoryResponse>;

  deleteCategory(request: DeleteCategoryRequest): Observable<DeleteCategoryResponse>;

  listCategories(request: ListCategoriesRequest): Observable<ListCategoriesResponse>;
}

/**
 * ---------------------
 * Service Definition
 * ---------------------
 */

export interface CategoryServiceController {
  createCategory(
    request: CreateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  getCategory(request: GetCategoryRequest): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  getAllCategories(
    request: GetAllCategoriesRequest,
  ): Promise<AllCategoriesWithMetaResponse> | Observable<AllCategoriesWithMetaResponse> | AllCategoriesWithMetaResponse;

  updateCategory(
    request: UpdateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  deleteCategory(
    request: DeleteCategoryRequest,
  ): Promise<DeleteCategoryResponse> | Observable<DeleteCategoryResponse> | DeleteCategoryResponse;

  listCategories(
    request: ListCategoriesRequest,
  ): Promise<ListCategoriesResponse> | Observable<ListCategoriesResponse> | ListCategoriesResponse;
}

export function CategoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createCategory",
      "getCategory",
      "getAllCategories",
      "updateCategory",
      "deleteCategory",
      "listCategories",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CategoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CategoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CATEGORY_SERVICE_NAME = "CategoryService";
