// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: job/interview.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "interview";

/**
 * ---------------------
 * Interview Messages
 * ---------------------
 */
export interface Interview {
  id: string;
  jobPostId: string;
  memberId: string;
  corporateId: string;
  roomId?: string | undefined;
  interviewDate?: string | undefined;
  status: string;
  failureReason?: string | undefined;
  createdAt: string;
  updatedAt: string;
  jobPost?: JobPost | undefined;
  reviews: Review[];
}

export interface JobPost {
  id: string;
  title?: string | undefined;
  corporateId: string;
}

export interface Review {
  id: string;
  interviewId: string;
  reviewerId: string;
  rating?: number | undefined;
  comment?: string | undefined;
  createdAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface InterviewResponse {
  success: boolean;
  message?: string | undefined;
  data?: Interview | undefined;
}

export interface ListInterviewResponse {
  message?: string | undefined;
  interview: Interview | undefined;
}

export interface AllInterviewsWithMetaResponse {
  data: Interview[];
  meta: PaginationMeta | undefined;
}

export interface DeleteInterviewResponse {
  success: boolean;
  message: string;
}

/**
 * ---------------------
 * CRUD Requests
 * ---------------------
 */
export interface CreateInterviewRequest {
  jobPostId: string;
  memberId: string;
  corporateId: string;
  roomId?: string | undefined;
  interviewDate?: string | undefined;
  status?: string | undefined;
  failureReason?: string | undefined;
}

export interface GetInterviewRequest {
  interviewId: string;
}

export interface GetAllInterviewsRequest {
  basicQuery: BasicQuery | undefined;
}

export interface UpdateInterviewRequest {
  interviewId: string;
  roomId?: string | undefined;
  interviewDate?: string | undefined;
  status?: string | undefined;
  failureReason?: string | undefined;
}

export interface DeleteInterviewRequest {
  interviewId: string;
}

export interface ListInterviewsRequest {
  page: number;
  limit: number;
  search?: string | undefined;
  jobPostId?: string | undefined;
  memberId?: string | undefined;
  corporateId?: string | undefined;
  status?: string | undefined;
}

export const INTERVIEW_PACKAGE_NAME = "interview";

/**
 * ---------------------
 * Service Definition
 * ---------------------
 */

export interface InterviewServiceClient {
  createInterview(request: CreateInterviewRequest): Observable<InterviewResponse>;

  getInterview(request: GetInterviewRequest): Observable<ListInterviewResponse>;

  getAllInterviews(request: GetAllInterviewsRequest): Observable<AllInterviewsWithMetaResponse>;

  updateInterview(request: UpdateInterviewRequest): Observable<InterviewResponse>;

  deleteInterview(request: DeleteInterviewRequest): Observable<DeleteInterviewResponse>;

  listInterviews(request: ListInterviewsRequest): Observable<AllInterviewsWithMetaResponse>;
}

/**
 * ---------------------
 * Service Definition
 * ---------------------
 */

export interface InterviewServiceController {
  createInterview(
    request: CreateInterviewRequest,
  ): Promise<InterviewResponse> | Observable<InterviewResponse> | InterviewResponse;

  getInterview(
    request: GetInterviewRequest,
  ): Promise<ListInterviewResponse> | Observable<ListInterviewResponse> | ListInterviewResponse;

  getAllInterviews(
    request: GetAllInterviewsRequest,
  ): Promise<AllInterviewsWithMetaResponse> | Observable<AllInterviewsWithMetaResponse> | AllInterviewsWithMetaResponse;

  updateInterview(
    request: UpdateInterviewRequest,
  ): Promise<InterviewResponse> | Observable<InterviewResponse> | InterviewResponse;

  deleteInterview(
    request: DeleteInterviewRequest,
  ): Promise<DeleteInterviewResponse> | Observable<DeleteInterviewResponse> | DeleteInterviewResponse;

  listInterviews(
    request: ListInterviewsRequest,
  ): Promise<AllInterviewsWithMetaResponse> | Observable<AllInterviewsWithMetaResponse> | AllInterviewsWithMetaResponse;
}

export function InterviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createInterview",
      "getInterview",
      "getAllInterviews",
      "updateInterview",
      "deleteInterview",
      "listInterviews",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INTERVIEW_SERVICE_NAME = "InterviewService";
