// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: job/job-post.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "jobpost";

/**
 * ---------------------
 * JobPost Messages
 * ---------------------
 */
export interface JobPost {
  id: string;
  corporateId: string;
  title?: string | undefined;
  description?: string | undefined;
  location?: string | undefined;
  salaryRange?: string | undefined;
  categoryId?: string | undefined;
  feeType?: string | undefined;
  status: string;
  approvedBy?: string | undefined;
  appliesCount?: number | undefined;
  createdAt: string;
  updatedAt: string;
  expiredAt?: string | undefined;
  category?: Category | undefined;
  applies: Apply[];
}

export interface Category {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
}

export interface Apply {
  id: string;
  jobPostId: string;
  userId: string;
  userInfoId?: string | undefined;
  isReviewed: boolean;
  status: string;
  appliedAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface JobPostResponse {
  success: boolean;
  message?: string | undefined;
  data?: JobPost | undefined;
}

export interface ListJobPostResponse {
  message?: string | undefined;
  jobPost: JobPost | undefined;
}

export interface AllJobPostsWithMetaResponse {
  data: JobPost[];
  meta: PaginationMeta | undefined;
}

export interface DeleteJobPostResponse {
  success: boolean;
  message: string;
}

/**
 * ---------------------
 * CRUD Requests
 * ---------------------
 */
export interface CreateJobPostRequest {
  title?: string | undefined;
  description?: string | undefined;
  location?: string | undefined;
  salaryRange?: string | undefined;
  categoryId?: string | undefined;
  feeType?: string | undefined;
  status?: string | undefined;
  expiredAt?: string | undefined;
  corporateId: string;
}

export interface GetJobPostRequest {
  jobPostId: string;
}

export interface GetAllJobPostsRequest {
  basicQuery: BasicQuery | undefined;
}

export interface UpdateJobPostRequest {
  jobPostId: string;
  title?: string | undefined;
  description?: string | undefined;
  location?: string | undefined;
  salaryRange?: string | undefined;
  categoryId?: string | undefined;
  feeType?: string | undefined;
  status?: string | undefined;
  expiredAt?: string | undefined;
  approvedBy?: string | undefined;
  appliesCount?: number | undefined;
}

export interface DeleteJobPostRequest {
  jobPostId: string;
}

export interface ListJobPostsRequest {
  page: number;
  limit: number;
  search?: string | undefined;
  corporateId?: string | undefined;
  categoryId?: string | undefined;
  status?: string | undefined;
}

export const JOBPOST_PACKAGE_NAME = "jobpost";

/**
 * ---------------------
 * Service Definition
 * ---------------------
 */

export interface JobPostServiceClient {
  createJobPost(request: CreateJobPostRequest): Observable<JobPostResponse>;

  getJobPost(request: GetJobPostRequest): Observable<ListJobPostResponse>;

  getAllJobPosts(request: GetAllJobPostsRequest): Observable<AllJobPostsWithMetaResponse>;

  updateJobPost(request: UpdateJobPostRequest): Observable<JobPostResponse>;

  deleteJobPost(request: DeleteJobPostRequest): Observable<DeleteJobPostResponse>;

  listJobPosts(request: ListJobPostsRequest): Observable<AllJobPostsWithMetaResponse>;
}

/**
 * ---------------------
 * Service Definition
 * ---------------------
 */

export interface JobPostServiceController {
  createJobPost(
    request: CreateJobPostRequest,
  ): Promise<JobPostResponse> | Observable<JobPostResponse> | JobPostResponse;

  getJobPost(
    request: GetJobPostRequest,
  ): Promise<ListJobPostResponse> | Observable<ListJobPostResponse> | ListJobPostResponse;

  getAllJobPosts(
    request: GetAllJobPostsRequest,
  ): Promise<AllJobPostsWithMetaResponse> | Observable<AllJobPostsWithMetaResponse> | AllJobPostsWithMetaResponse;

  updateJobPost(
    request: UpdateJobPostRequest,
  ): Promise<JobPostResponse> | Observable<JobPostResponse> | JobPostResponse;

  deleteJobPost(
    request: DeleteJobPostRequest,
  ): Promise<DeleteJobPostResponse> | Observable<DeleteJobPostResponse> | DeleteJobPostResponse;

  listJobPosts(
    request: ListJobPostsRequest,
  ): Promise<AllJobPostsWithMetaResponse> | Observable<AllJobPostsWithMetaResponse> | AllJobPostsWithMetaResponse;
}

export function JobPostServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createJobPost",
      "getJobPost",
      "getAllJobPosts",
      "updateJobPost",
      "deleteJobPost",
      "listJobPosts",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("JobPostService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("JobPostService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const JOB_POST_SERVICE_NAME = "JobPostService";
