// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: job/report.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "reports";

/** Enums */
export enum ReportStatus {
  REPORT_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  UNDER_REVIEW = 2,
  RESOLVED = 3,
  REJECTED = 4,
  CLOSED = 5,
  UNRECOGNIZED = -1,
}

/** Message */
export interface Report {
  id: string;
  title?: string | undefined;
  reporterId: string;
  reportedUserId: string;
  reason?: string | undefined;
  status: ReportStatus;
  createdAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface ReportResponse {
  success: boolean;
  message?: string | undefined;
}

export interface ListReportsResponse {
  reports: Report[];
  total: number;
  page: number;
  limit: number;
}

export interface DeleteReportResponse {
  success: boolean;
  message: string;
}

export interface AllReportsWithMetaResponse {
  data: Report[];
  meta: PaginationMeta | undefined;
}

export interface SingleReportResponse {
  message?: string | undefined;
  report: Report | undefined;
}

/**
 * ---------------------
 * CRUD Requests
 * ---------------------
 */
export interface ListReportsRequest {
  page: number;
  limit: number;
  status?: ReportStatus | undefined;
  reporterId?: string | undefined;
  reportedUserId?: string | undefined;
}

export interface GetReportRequest {
  reportId: string;
}

export interface UpdateReportRequest {
  reportId: string;
  title?: string | undefined;
  reason?: string | undefined;
  status?: ReportStatus | undefined;
}

export interface DeleteReportRequest {
  reportId: string;
}

export interface GetAllReportsRequest {
  basicQuery: BasicQuery | undefined;
}

export interface CreateReportRequest {
  title?: string | undefined;
  reporterId: string;
  reportedUserId: string;
  reason?: string | undefined;
  status?: ReportStatus | undefined;
}

export const REPORTS_PACKAGE_NAME = "reports";

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface ReportServiceClient {
  createReport(request: CreateReportRequest): Observable<ReportResponse>;

  getReport(request: GetReportRequest): Observable<SingleReportResponse>;

  getAllReports(request: GetAllReportsRequest): Observable<AllReportsWithMetaResponse>;

  updateReport(request: UpdateReportRequest): Observable<ReportResponse>;

  deleteReport(request: DeleteReportRequest): Observable<DeleteReportResponse>;

  listReports(request: ListReportsRequest): Observable<ListReportsResponse>;
}

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface ReportServiceController {
  createReport(request: CreateReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;

  getReport(
    request: GetReportRequest,
  ): Promise<SingleReportResponse> | Observable<SingleReportResponse> | SingleReportResponse;

  getAllReports(
    request: GetAllReportsRequest,
  ): Promise<AllReportsWithMetaResponse> | Observable<AllReportsWithMetaResponse> | AllReportsWithMetaResponse;

  updateReport(request: UpdateReportRequest): Promise<ReportResponse> | Observable<ReportResponse> | ReportResponse;

  deleteReport(
    request: DeleteReportRequest,
  ): Promise<DeleteReportResponse> | Observable<DeleteReportResponse> | DeleteReportResponse;

  listReports(
    request: ListReportsRequest,
  ): Promise<ListReportsResponse> | Observable<ListReportsResponse> | ListReportsResponse;
}

export function ReportServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createReport",
      "getReport",
      "getAllReports",
      "updateReport",
      "deleteReport",
      "listReports",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReportService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReportService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REPORT_SERVICE_NAME = "ReportService";
