// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: job/review.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "reviews";

/** Message */
export interface Review {
  id: string;
  interviewId: string;
  reviewerId: string;
  rating?: number | undefined;
  comment?: string | undefined;
  createdAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface ReviewResponse {
  success: boolean;
  message?: string | undefined;
}

export interface ListReviewsResponse {
  reviews: Review[];
  total: number;
  page: number;
  limit: number;
}

export interface DeleteReviewResponse {
  success: boolean;
  message: string;
}

export interface AllReviewsWithMetaResponse {
  data: Review[];
  meta: PaginationMeta | undefined;
}

export interface SingleReviewResponse {
  message?: string | undefined;
  review: Review | undefined;
}

/**
 * ---------------------
 * CRUD Requests
 * ---------------------
 */
export interface ListReviewsRequest {
  page: number;
  limit: number;
  rating?: number | undefined;
  reviewerId?: string | undefined;
  interviewId?: string | undefined;
}

export interface GetReviewRequest {
  reviewId: string;
}

export interface UpdateReviewRequest {
  reviewId: string;
  rating?: number | undefined;
  comment?: string | undefined;
}

export interface DeleteReviewRequest {
  reviewId: string;
}

export interface GetAllReviewsRequest {
  basicQuery: BasicQuery | undefined;
}

export interface CreateReviewRequest {
  interviewId: string;
  reviewerId: string;
  rating?: number | undefined;
  comment?: string | undefined;
}

export const REVIEWS_PACKAGE_NAME = "reviews";

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface ReviewServiceClient {
  createReview(request: CreateReviewRequest): Observable<ReviewResponse>;

  getReview(request: GetReviewRequest): Observable<SingleReviewResponse>;

  getAllReviews(request: GetAllReviewsRequest): Observable<AllReviewsWithMetaResponse>;

  updateReview(request: UpdateReviewRequest): Observable<ReviewResponse>;

  deleteReview(request: DeleteReviewRequest): Observable<DeleteReviewResponse>;

  listReviews(request: ListReviewsRequest): Observable<ListReviewsResponse>;
}

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface ReviewServiceController {
  createReview(request: CreateReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  getReview(
    request: GetReviewRequest,
  ): Promise<SingleReviewResponse> | Observable<SingleReviewResponse> | SingleReviewResponse;

  getAllReviews(
    request: GetAllReviewsRequest,
  ): Promise<AllReviewsWithMetaResponse> | Observable<AllReviewsWithMetaResponse> | AllReviewsWithMetaResponse;

  updateReview(request: UpdateReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  deleteReview(
    request: DeleteReviewRequest,
  ): Promise<DeleteReviewResponse> | Observable<DeleteReviewResponse> | DeleteReviewResponse;

  listReviews(
    request: ListReviewsRequest,
  ): Promise<ListReviewsResponse> | Observable<ListReviewsResponse> | ListReviewsResponse;
}

export function ReviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createReview",
      "getReview",
      "getAllReviews",
      "updateReview",
      "deleteReview",
      "listReviews",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REVIEW_SERVICE_NAME = "ReviewService";
