import { Injectable, Logger } from '@nestjs/common';

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  //   async queueEmail(emailData: EmailQueueDto): Promise<EmailSendingResponseDto> {
  //   try {
  //     const priority = this.emailQueueService.getPriorityByType(emailData.type);

  //     const emailId = await this.emailQueueService.addToQueue({
  //       userId: emailData.userId,
  //       email: emailData.email,
  //       subject: emailData.subject,
  //       content: emailData.content,
  //       type: emailData.type,
  //       priority,
  //       metadata: emailData.metadata,
  //       maxAttempts: 3,
  //     });

  //     return {
  //       id: emailId,
  //       status: 'queued',
  //       message: 'Email has been queued for sending',
  //     };
  //   } catch (error) {
  //     this.logger.error('Failed to queue email:', error);
  //     return {
  //       id: '',
  //       status: 'error',
  //       message: 'Failed to queue email',
  //     };
  //   }
  // }
  //   async handleEmailVerification(data: {
  //   userId?: string;
  //   email: string;
  //   verificationToken: string;
  //   verificationUrl: string;
  // }): Promise<EmailSendingResponseDto> {
  //   const verificationData: EmailVerificationData = {
  //     verificationToken: data.verificationToken,
  //     verificationUrl: data.verificationUrl,
  //   };

  //   return this.queueEmail({
  //     userId: data.userId,
  //     email: data.email,
  //     subject: 'Verify Your Email Address',
  //     content: '', // Will be generated by template
  //     type: EmailType.EMAIL_VERIFICATION,
  //     metadata: verificationData,
  //   });
  // }
}
