/**
 * 교육기관 확장 Seed 데이터 / Extended educational institutions seed data
 *
 * 국내 주요 대학 100개 + 어학당 50개
 * 100 major Korean universities + 50 language institutes
 */

import { InstitutionSeedData } from './educational-institutions.seed';

export const EXTENDED_UNIVERSITIES: InstitutionSeedData[] = [
  // ===== 수도권 추가 대학교 (30개) =====
  {
    name: '한국외국어대학교',
    nameEn: 'Hankuk University of Foreign Studies',
    type: 'UNIVERSITY',
    address: '서울특별시 동대문구 이문로 107',
    latitude: 37.5965,
    longitude: 127.0587,
    isMetroArea: true,
    searchKeywords: ['한국외대', '외대', 'HUFS', 'Hankuk', '한국외국어대학교'],
  },
  {
    name: '서울시립대학교',
    nameEn: 'University of Seoul',
    type: 'UNIVERSITY',
    address: '서울특별시 동대문구 서울시립대로 163',
    latitude: 37.5836,
    longitude: 127.0596,
    isMetroArea: true,
    searchKeywords: ['서울시립대', '시립대', 'UOS', '서울시립대학교'],
  },
  {
    name: '광운대학교',
    nameEn: 'Kwangwoon University',
    type: 'UNIVERSITY',
    address: '서울특별시 노원구 광운로 20',
    latitude: 37.6199,
    longitude: 127.0589,
    isMetroArea: true,
    searchKeywords: ['광운대', 'KW', 'Kwangwoon', '광운대학교'],
  },
  {
    name: '명지대학교',
    nameEn: 'Myongji University',
    type: 'UNIVERSITY',
    address: '서울특별시 서대문구 거북골로 34',
    latitude: 37.5789,
    longitude: 126.9253,
    isMetroArea: true,
    searchKeywords: ['명지대', 'MJU', 'Myongji', '명지대학교'],
  },
  {
    name: '상명대학교',
    nameEn: 'Sangmyung University',
    type: 'UNIVERSITY',
    address: '서울특별시 종로구 홍지문2길 20',
    latitude: 37.5943,
    longitude: 126.9627,
    isMetroArea: true,
    searchKeywords: ['상명대', 'SMU', 'Sangmyung', '상명대학교'],
  },
  {
    name: '덕성여자대학교',
    nameEn: 'Duksung Women\'s University',
    type: 'UNIVERSITY',
    address: '서울특별시 도봉구 삼양로144길 33',
    latitude: 37.6532,
    longitude: 127.0169,
    isMetroArea: true,
    searchKeywords: ['덕성여대', 'Duksung', '덕성여자대학교'],
  },
  {
    name: '동덕여자대학교',
    nameEn: 'Dongduk Women\'s University',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 화랑로13길 60',
    latitude: 37.6065,
    longitude: 127.0426,
    isMetroArea: true,
    searchKeywords: ['동덕여대', 'Dongduk', '동덕여자대학교'],
  },
  {
    name: '성신여자대학교',
    nameEn: 'Sungshin Women\'s University',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 보문로34다길 2',
    latitude: 37.5925,
    longitude: 127.0168,
    isMetroArea: true,
    searchKeywords: ['성신여대', 'Sungshin', '성신여자대학교'],
  },
  {
    name: '한성대학교',
    nameEn: 'Hansung University',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 삼선교로16길 116',
    latitude: 37.5827,
    longitude: 127.0090,
    isMetroArea: true,
    searchKeywords: ['한성대', 'Hansung', '한성대학교'],
  },
  {
    name: '서울과학기술대학교',
    nameEn: 'Seoul National University of Science and Technology',
    type: 'UNIVERSITY',
    address: '서울특별시 노원구 공릉로 232',
    latitude: 37.6316,
    longitude: 127.0787,
    isMetroArea: true,
    searchKeywords: ['서울과기대', '과기대', 'SeoulTech', '서울과학기술대학교'],
  },
  {
    name: '삼육대학교',
    nameEn: 'Sahmyook University',
    type: 'UNIVERSITY',
    address: '서울특별시 노원구 화랑로 815',
    latitude: 37.6444,
    longitude: 127.1068,
    isMetroArea: true,
    searchKeywords: ['삼육대', 'Sahmyook', '삼육대학교'],
  },
  {
    name: '경기대학교',
    nameEn: 'Kyonggi University',
    type: 'UNIVERSITY',
    address: '경기도 수원시 영통구 광교산로 154-42',
    latitude: 37.3000,
    longitude: 127.0357,
    isMetroArea: true,
    searchKeywords: ['경기대', 'KGU', 'Kyonggi', '경기대학교'],
  },
  {
    name: '한국항공대학교',
    nameEn: 'Korea Aerospace University',
    type: 'UNIVERSITY',
    address: '경기도 고양시 덕양구 화전동 항공대학로 76',
    latitude: 37.6008,
    longitude: 126.8649,
    isMetroArea: true,
    searchKeywords: ['한국항공대', '항공대', 'KAU', '한국항공대학교'],
  },
  {
    name: '한국산업기술대학교',
    nameEn: 'Korea Polytechnic University',
    type: 'UNIVERSITY',
    address: '경기도 시흥시 산업대학로 237',
    latitude: 37.3415,
    longitude: 126.7349,
    isMetroArea: true,
    searchKeywords: ['산기대', 'KPU', '한국산업기술대학교'],
  },
  {
    name: '수원대학교',
    nameEn: 'The University of Suwon',
    type: 'UNIVERSITY',
    address: '경기도 화성시 봉담읍 와우안길 17',
    latitude: 37.2422,
    longitude: 126.9598,
    isMetroArea: true,
    searchKeywords: ['수원대', 'USW', '수원대학교'],
  },
  {
    name: '용인대학교',
    nameEn: 'Yongin University',
    type: 'UNIVERSITY',
    address: '경기도 용인시 처인구 삼가동 470',
    latitude: 37.2389,
    longitude: 127.1860,
    isMetroArea: true,
    searchKeywords: ['용인대', 'YIU', '용인대학교'],
  },
  {
    name: '한국외국어대학교 글로벌캠퍼스',
    nameEn: 'HUFS Global Campus',
    type: 'UNIVERSITY',
    address: '경기도 용인시 처인구 모현읍 외대로 81',
    latitude: 37.3378,
    longitude: 127.2643,
    isMetroArea: true,
    searchKeywords: ['한국외대 글로벌', '외대 글로벌', 'HUFS Global'],
  },
  {
    name: '경희대학교 국제캠퍼스',
    nameEn: 'Kyung Hee University Global Campus',
    type: 'UNIVERSITY',
    address: '경기도 용인시 기흥구 덕영대로 1732',
    latitude: 37.2430,
    longitude: 127.0782,
    isMetroArea: true,
    searchKeywords: ['경희대 국제', 'KHU Global', '경희대학교 국제캠퍼스'],
  },
  {
    name: '중앙대학교 안성캠퍼스',
    nameEn: 'Chung-Ang University Anseong Campus',
    type: 'UNIVERSITY',
    address: '경기도 안성시 대덕면 서동대로 4726',
    latitude: 37.1066,
    longitude: 127.2694,
    isMetroArea: true,
    searchKeywords: ['중앙대 안성', 'CAU Anseong', '중앙대학교 안성'],
  },
  {
    name: '한양대학교 ERICA캠퍼스',
    nameEn: 'Hanyang University ERICA Campus',
    type: 'UNIVERSITY',
    address: '경기도 안산시 상록구 한양대학로 55',
    latitude: 37.2975,
    longitude: 126.8367,
    isMetroArea: true,
    searchKeywords: ['한양대 에리카', 'Hanyang ERICA', '한양대학교 ERICA'],
  },

  // ===== 지방 국립대 (20개) =====
  {
    name: '경상국립대학교',
    nameEn: 'Gyeongsang National University',
    type: 'UNIVERSITY',
    address: '경남 진주시 진주대로 501',
    latitude: 35.1556,
    longitude: 128.0961,
    isMetroArea: false,
    searchKeywords: ['경상국립대', '경상대', 'GNU', '경상국립대학교'],
  },
  {
    name: '제주대학교',
    nameEn: 'Jeju National University',
    type: 'UNIVERSITY',
    address: '제주특별자치도 제주시 제주대학로 102',
    latitude: 33.4569,
    longitude: 126.5605,
    isMetroArea: false,
    searchKeywords: ['제주대', 'JNU', '제주대학교'],
  },
  {
    name: '충북대학교',
    nameEn: 'Chungbuk National University',
    type: 'UNIVERSITY',
    address: '충북 청주시 서원구 충대로 1',
    latitude: 36.6279,
    longitude: 127.4572,
    isMetroArea: false,
    searchKeywords: ['충북대', 'CBNU', '충북대학교'],
  },
  {
    name: '강릉원주대학교',
    nameEn: 'Gangneung-Wonju National University',
    type: 'UNIVERSITY',
    address: '강원 강릉시 죽헌길 7',
    latitude: 37.7707,
    longitude: 128.8704,
    isMetroArea: false,
    searchKeywords: ['강릉원주대', 'GWNU', '강릉원주대학교'],
  },
  {
    name: '목포대학교',
    nameEn: 'Mokpo National University',
    type: 'UNIVERSITY',
    address: '전남 무안군 청계면 영산로 1666',
    latitude: 34.9130,
    longitude: 126.4375,
    isMetroArea: false,
    searchKeywords: ['목포대', 'MNU', '목포대학교'],
  },
  {
    name: '순천대학교',
    nameEn: 'Sunchon National University',
    type: 'UNIVERSITY',
    address: '전남 순천시 중앙로 255',
    latitude: 34.9570,
    longitude: 127.5285,
    isMetroArea: false,
    searchKeywords: ['순천대', 'SCNU', '순천대학교'],
  },
  {
    name: '군산대학교',
    nameEn: 'Kunsan National University',
    type: 'UNIVERSITY',
    address: '전북 군산시 대학로 558',
    latitude: 35.9465,
    longitude: 126.7052,
    isMetroArea: false,
    searchKeywords: ['군산대', 'KNU', '군산대학교'],
  },
  {
    name: '안동대학교',
    nameEn: 'Andong National University',
    type: 'UNIVERSITY',
    address: '경북 안동시 경동로 1375',
    latitude: 36.5437,
    longitude: 128.7990,
    isMetroArea: false,
    searchKeywords: ['안동대', 'ANU', '안동대학교'],
  },
  {
    name: '경북대학교 상주캠퍼스',
    nameEn: 'Kyungpook National University Sangju Campus',
    type: 'UNIVERSITY',
    address: '경북 상주시 가장동 386',
    latitude: 36.3912,
    longitude: 128.1395,
    isMetroArea: false,
    searchKeywords: ['경북대 상주', 'KNU Sangju', '경북대학교 상주'],
  },
  {
    name: '창원대학교',
    nameEn: 'Changwon National University',
    type: 'UNIVERSITY',
    address: '경남 창원시 의창구 창원대학로 20',
    latitude: 35.2431,
    longitude: 128.6928,
    isMetroArea: false,
    searchKeywords: ['창원대', 'CWNU', '창원대학교'],
  },

  // ===== 지방 주요 사립대 (30개) =====
  {
    name: '영남대학교',
    nameEn: 'Yeungnam University',
    type: 'UNIVERSITY',
    address: '대구광역시 경산시 대학로 280',
    latitude: 35.8326,
    longitude: 128.7548,
    isMetroArea: false,
    searchKeywords: ['영남대', 'YU', 'Yeungnam', '영남대학교'],
  },
  {
    name: '계명대학교',
    nameEn: 'Keimyung University',
    type: 'UNIVERSITY',
    address: '대구광역시 달서구 달구벌대로 1095',
    latitude: 35.8551,
    longitude: 128.4894,
    isMetroArea: false,
    searchKeywords: ['계명대', 'KMU', 'Keimyung', '계명대학교'],
  },
  {
    name: '동아대학교',
    nameEn: 'Dong-A University',
    type: 'UNIVERSITY',
    address: '부산광역시 사하구 낙동대로 550번길 37',
    latitude: 35.1236,
    longitude: 128.9697,
    isMetroArea: false,
    searchKeywords: ['동아대', 'DAU', 'Dong-A', '동아대학교'],
  },
  {
    name: '부경대학교',
    nameEn: 'Pukyong National University',
    type: 'UNIVERSITY',
    address: '부산광역시 남구 용소로 45',
    latitude: 35.1337,
    longitude: 129.1018,
    isMetroArea: false,
    searchKeywords: ['부경대', 'PKNU', 'Pukyong', '부경대학교'],
  },
  {
    name: '인제대학교',
    nameEn: 'Inje University',
    type: 'UNIVERSITY',
    address: '경남 김해시 인제로 197',
    latitude: 35.2536,
    longitude: 128.8663,
    isMetroArea: false,
    searchKeywords: ['인제대', 'Inje', '인제대학교'],
  },
  {
    name: '조선대학교',
    nameEn: 'Chosun University',
    type: 'UNIVERSITY',
    address: '광주광역시 동구 필문대로 309',
    latitude: 35.1395,
    longitude: 126.9277,
    isMetroArea: false,
    searchKeywords: ['조선대', 'Chosun', '조선대학교'],
  },
  {
    name: '호남대학교',
    nameEn: 'Honam University',
    type: 'UNIVERSITY',
    address: '광주광역시 광산구 호남대학로 120',
    latitude: 35.1762,
    longitude: 126.7306,
    isMetroArea: false,
    searchKeywords: ['호남대', 'Honam', '호남대학교'],
  },
  {
    name: '원광대학교',
    nameEn: 'Wonkwang University',
    type: 'UNIVERSITY',
    address: '전북 익산시 익산대로 460',
    latitude: 35.9680,
    longitude: 126.9577,
    isMetroArea: false,
    searchKeywords: ['원광대', 'WKU', 'Wonkwang', '원광대학교'],
  },
  {
    name: '우석대학교',
    nameEn: 'Woosuk University',
    type: 'UNIVERSITY',
    address: '전북 완주군 삼례읍 삼례로 443',
    latitude: 35.9048,
    longitude: 127.0749,
    isMetroArea: false,
    searchKeywords: ['우석대', 'Woosuk', '우석대학교'],
  },
  {
    name: '대구가톨릭대학교',
    nameEn: 'Daegu Catholic University',
    type: 'UNIVERSITY',
    address: '경북 경산시 하양읍 하양로 13-13',
    latitude: 35.9066,
    longitude: 128.8189,
    isMetroArea: false,
    searchKeywords: ['대구가톨릭대', '대가대', 'DCU', '대구가톨릭대학교'],
  },
  {
    name: '인하대학교',
    nameEn: 'Inha University',
    type: 'UNIVERSITY',
    address: '인천광역시 미추홀구 인하로 100',
    latitude: 37.4502,
    longitude: 126.6562,
    isMetroArea: true,
    searchKeywords: ['인하대', 'Inha', '인하대학교'],
  },
  {
    name: '가천대학교',
    nameEn: 'Gachon University',
    type: 'UNIVERSITY',
    address: '경기도 성남시 수정구 성남대로 1342',
    latitude: 37.4505,
    longitude: 127.1283,
    isMetroArea: true,
    searchKeywords: ['가천대', 'Gachon', '가천대학교'],
  },
  {
    name: '단국대학교 죽전캠퍼스',
    nameEn: 'Dankook University Jukjeon Campus',
    type: 'UNIVERSITY',
    address: '경기도 용인시 수지구 죽전로 152',
    latitude: 37.3226,
    longitude: 127.1262,
    isMetroArea: true,
    searchKeywords: ['단국대 죽전', 'DKU Jukjeon', '단국대학교 죽전'],
  },
  {
    name: '단국대학교 천안캠퍼스',
    nameEn: 'Dankook University Cheonan Campus',
    type: 'UNIVERSITY',
    address: '충남 천안시 동남구 단대로 119',
    latitude: 36.8054,
    longitude: 127.1945,
    isMetroArea: false,
    searchKeywords: ['단국대 천안', 'DKU Cheonan', '단국대학교 천안'],
  },
  {
    name: '아주대학교',
    nameEn: 'Ajou University',
    type: 'UNIVERSITY',
    address: '경기도 수원시 영통구 월드컵로 206',
    latitude: 37.2813,
    longitude: 127.0442,
    isMetroArea: true,
    searchKeywords: ['아주대', 'Ajou', '아주대학교'],
  },
  {
    name: '가톨릭대학교',
    nameEn: 'Catholic University of Korea',
    type: 'UNIVERSITY',
    address: '경기도 부천시 원미구 지봉로 43',
    latitude: 37.4863,
    longitude: 126.8014,
    isMetroArea: true,
    searchKeywords: ['가톨릭대', '가대', 'CUK', '가톨릭대학교'],
  },
  {
    name: '성균관대학교 자연과학캠퍼스',
    nameEn: 'Sungkyunkwan University Natural Sciences Campus',
    type: 'UNIVERSITY',
    address: '경기도 수원시 장안구 서부로 2066',
    latitude: 37.2935,
    longitude: 126.9752,
    isMetroArea: true,
    searchKeywords: ['성균관대 자과캠', '성대 자과캠', 'SKKU 수원'],
  },
  {
    name: '숙명여자대학교',
    nameEn: 'Sookmyung Women\'s University',
    type: 'UNIVERSITY',
    address: '서울특별시 용산구 청파로47길 100',
    latitude: 37.5448,
    longitude: 126.9652,
    isMetroArea: true,
    searchKeywords: ['숙명여대', 'Sookmyung', '숙명여자대학교'],
  },
  {
    name: '이화여자대학교',
    nameEn: 'Ewha Womans University',
    type: 'UNIVERSITY',
    address: '서울특별시 서대문구 이화여대길 52',
    latitude: 37.5617,
    longitude: 126.9466,
    isMetroArea: true,
    searchKeywords: ['이화여대', '이대', 'Ewha', '이화여자대학교'],
  },
  {
    name: '한국예술종합학교',
    nameEn: 'Korea National University of Arts',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 화랑로32길 146-37',
    latitude: 37.6025,
    longitude: 127.0621,
    isMetroArea: true,
    searchKeywords: ['한예종', 'K-Arts', 'KNUA', '한국예술종합학교'],
  },
  {
    name: '서울교육대학교',
    nameEn: 'Seoul National University of Education',
    type: 'UNIVERSITY',
    address: '서울특별시 서초구 서초중앙로 96',
    latitude: 37.4929,
    longitude: 127.0143,
    isMetroArea: true,
    searchKeywords: ['서울교대', 'SNUE', '서울교육대학교'],
  },
  {
    name: '경인교육대학교',
    nameEn: 'Gyeongin National University of Education',
    type: 'UNIVERSITY',
    address: '인천광역시 계양구 계산로 62',
    latitude: 37.5409,
    longitude: 126.7269,
    isMetroArea: true,
    searchKeywords: ['경인교대', 'GINUE', '경인교육대학교'],
  },
  {
    name: '협성대학교',
    nameEn: 'Hyupsung University',
    type: 'UNIVERSITY',
    address: '경기도 화성시 봉담읍 협성로 72',
    latitude: 37.2267,
    longitude: 126.9323,
    isMetroArea: true,
    searchKeywords: ['협성대', 'Hyupsung', '협성대학교'],
  },
  {
    name: '평택대학교',
    nameEn: 'Pyeongtaek University',
    type: 'UNIVERSITY',
    address: '경기도 평택시 서동대로 3825',
    latitude: 36.9918,
    longitude: 127.0883,
    isMetroArea: true,
    searchKeywords: ['평택대', 'PTU', '평택대학교'],
  },
  {
    name: '서울한영대학교',
    nameEn: 'Seoul Hanyoung University',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 삼선교로16길 13',
    latitude: 37.5862,
    longitude: 127.0095,
    isMetroArea: true,
    searchKeywords: ['서울한영대', '한영대', '서울한영대학교'],
  },
  {
    name: '서울여자대학교',
    nameEn: 'Seoul Women\'s University',
    type: 'UNIVERSITY',
    address: '서울특별시 노원구 화랑로 621',
    latitude: 37.6256,
    longitude: 127.0913,
    isMetroArea: true,
    searchKeywords: ['서울여대', 'SWU', '서울여자대학교'],
  },
  {
    name: '서울장신대학교',
    nameEn: 'Seoul Jangsin University',
    type: 'UNIVERSITY',
    address: '경기도 광주시 도척면 도척윗로 423',
    latitude: 37.3685,
    longitude: 127.2537,
    isMetroArea: true,
    searchKeywords: ['서울장신대', '장신대', '서울장신대학교'],
  },
  {
    name: '총신대학교',
    nameEn: 'Chongshin University',
    type: 'UNIVERSITY',
    address: '서울특별시 동작구 사당로 143',
    latitude: 37.4873,
    longitude: 126.9810,
    isMetroArea: true,
    searchKeywords: ['총신대', 'Chongshin', '총신대학교'],
  },

  // ===== 지방 국립대 추가 (40개) =====
  {
    name: '부산대학교',
    nameEn: 'Pusan National University',
    type: 'UNIVERSITY',
    address: '부산광역시 금정구 부산대학로63번길 2',
    latitude: 35.2315,
    longitude: 129.0836,
    isMetroArea: false,
    searchKeywords: ['부산대', 'PNU', '부산대학교'],
  },
  {
    name: '전북대학교',
    nameEn: 'Jeonbuk National University',
    type: 'UNIVERSITY',
    address: '전북 전주시 덕진구 백제대로 567',
    latitude: 35.8464,
    longitude: 127.1291,
    isMetroArea: false,
    searchKeywords: ['전북대', 'JBNU', '전북대학교'],
  },
  {
    name: '전남대학교',
    nameEn: 'Chonnam National University',
    type: 'UNIVERSITY',
    address: '광주광역시 북구 용봉로 77',
    latitude: 35.1752,
    longitude: 126.9080,
    isMetroArea: false,
    searchKeywords: ['전남대', 'CNU', '전남대학교'],
  },
  {
    name: '경북대학교',
    nameEn: 'Kyungpook National University',
    type: 'UNIVERSITY',
    address: '대구광역시 북구 대학로 80',
    latitude: 35.8889,
    longitude: 128.6113,
    isMetroArea: false,
    searchKeywords: ['경북대', 'KNU', '경북대학교'],
  },
  {
    name: '충남대학교',
    nameEn: 'Chungnam National University',
    type: 'UNIVERSITY',
    address: '대전광역시 유성구 대학로 99',
    latitude: 36.3666,
    longitude: 127.3447,
    isMetroArea: false,
    searchKeywords: ['충남대', 'CNU', '충남대학교'],
  },
  {
    name: '강원대학교',
    nameEn: 'Kangwon National University',
    type: 'UNIVERSITY',
    address: '강원 춘천시 강원대학길 1',
    latitude: 37.8691,
    longitude: 127.7442,
    isMetroArea: false,
    searchKeywords: ['강원대', 'KNU', '강원대학교'],
  },
  {
    name: '한국해양대학교',
    nameEn: 'Korea Maritime & Ocean University',
    type: 'UNIVERSITY',
    address: '부산광역시 영도구 태종로 727',
    latitude: 35.0768,
    longitude: 129.0854,
    isMetroArea: false,
    searchKeywords: ['한국해양대', '해양대', 'KMOU', '한국해양대학교'],
  },
  {
    name: '한국교원대학교',
    nameEn: 'Korea National University of Education',
    type: 'UNIVERSITY',
    address: '충북 청주시 흥덕구 강내면 태성탑연로 250',
    latitude: 36.6283,
    longitude: 127.2882,
    isMetroArea: false,
    searchKeywords: ['한국교원대', '교원대', 'KNUE', '한국교원대학교'],
  },
  {
    name: '한국전통문화대학교',
    nameEn: 'Korea National University of Cultural Heritage',
    type: 'UNIVERSITY',
    address: '충남 부여군 규암면 백제문로 367',
    latitude: 36.2945,
    longitude: 126.8990,
    isMetroArea: false,
    searchKeywords: ['한국전통문화대', '전통문화대', 'KNUCH', '한국전통문화대학교'],
  },
  {
    name: '한국체육대학교',
    nameEn: 'Korea National Sport University',
    type: 'UNIVERSITY',
    address: '서울특별시 송파구 올림픽로 1239',
    latitude: 37.5234,
    longitude: 127.1237,
    isMetroArea: true,
    searchKeywords: ['한국체육대', '체대', 'KNSU', '한국체육대학교'],
  },
  {
    name: '공주대학교',
    nameEn: 'Kongju National University',
    type: 'UNIVERSITY',
    address: '충남 공주시 공주대학로 56',
    latitude: 36.4711,
    longitude: 127.1389,
    isMetroArea: false,
    searchKeywords: ['공주대', 'KNU', '공주대학교'],
  },
  {
    name: '공주교육대학교',
    nameEn: 'Gongju National University of Education',
    type: 'UNIVERSITY',
    address: '충남 공주시 봉황로 27',
    latitude: 36.4637,
    longitude: 127.1209,
    isMetroArea: false,
    searchKeywords: ['공주교대', 'GNUE', '공주교육대학교'],
  },
  {
    name: '청주교육대학교',
    nameEn: 'Cheongju National University of Education',
    type: 'UNIVERSITY',
    address: '충북 청주시 흥덕구 강내면 청주교대로 1',
    latitude: 36.6351,
    longitude: 127.2843,
    isMetroArea: false,
    searchKeywords: ['청주교대', 'CJNUE', '청주교육대학교'],
  },
  {
    name: '춘천교육대학교',
    nameEn: 'Chuncheon National University of Education',
    type: 'UNIVERSITY',
    address: '강원 춘천시 공지로 126',
    latitude: 37.8657,
    longitude: 127.7440,
    isMetroArea: false,
    searchKeywords: ['춘천교대', 'CNUE', '춘천교육대학교'],
  },
  {
    name: '대구교육대학교',
    nameEn: 'Daegu National University of Education',
    type: 'UNIVERSITY',
    address: '대구광역시 남구 중앙대로 219',
    latitude: 35.8582,
    longitude: 128.5638,
    isMetroArea: false,
    searchKeywords: ['대구교대', 'DNUE', '대구교육대학교'],
  },
  {
    name: '부산교육대학교',
    nameEn: 'Busan National University of Education',
    type: 'UNIVERSITY',
    address: '부산광역시 연제구 교대로 24',
    latitude: 35.1733,
    longitude: 129.0806,
    isMetroArea: false,
    searchKeywords: ['부산교대', 'BNUE', '부산교육대학교'],
  },
  {
    name: '광주교육대학교',
    nameEn: 'Gwangju National University of Education',
    type: 'UNIVERSITY',
    address: '광주광역시 북구 필문대로 55',
    latitude: 35.1737,
    longitude: 126.9161,
    isMetroArea: false,
    searchKeywords: ['광주교대', 'GNUE', '광주교육대학교'],
  },
  {
    name: '전주교육대학교',
    nameEn: 'Jeonju National University of Education',
    type: 'UNIVERSITY',
    address: '전북 전주시 완산구 가련산로 50',
    latitude: 35.8187,
    longitude: 127.1033,
    isMetroArea: false,
    searchKeywords: ['전주교대', 'JNUE', '전주교육대학교'],
  },
  {
    name: '진주교육대학교',
    nameEn: 'Jinju National University of Education',
    type: 'UNIVERSITY',
    address: '경남 진주시 진양호로 380',
    latitude: 35.1704,
    longitude: 128.0662,
    isMetroArea: false,
    searchKeywords: ['진주교대', 'JNUE', '진주교육대학교'],
  },
  {
    name: '금오공과대학교',
    nameEn: 'Kumoh National Institute of Technology',
    type: 'UNIVERSITY',
    address: '경북 구미시 대학로 61',
    latitude: 36.1453,
    longitude: 128.4139,
    isMetroArea: false,
    searchKeywords: ['금오공대', 'KIT', '금오공과대학교'],
  },
  {
    name: '한밭대학교',
    nameEn: 'Hanbat National University',
    type: 'UNIVERSITY',
    address: '대전광역시 유성구 동서대로 125',
    latitude: 36.3500,
    longitude: 127.3015,
    isMetroArea: false,
    searchKeywords: ['한밭대', 'HBNU', '한밭대학교'],
  },
  {
    name: '한국방송통신대학교',
    nameEn: 'Korea National Open University',
    type: 'UNIVERSITY',
    address: '서울특별시 종로구 대학로 86',
    latitude: 37.5838,
    longitude: 127.0012,
    isMetroArea: true,
    searchKeywords: ['방송대', '방통대', 'KNOU', '한국방송통신대학교'],
  },
  {
    name: '한경국립대학교',
    nameEn: 'Hankyong National University',
    type: 'UNIVERSITY',
    address: '경기도 안성시 중앙로 327',
    latitude: 37.0089,
    longitude: 127.2712,
    isMetroArea: true,
    searchKeywords: ['한경대', 'HKU', '한경국립대학교'],
  },
  {
    name: '순천향대학교',
    nameEn: 'Soonchunhyang University',
    type: 'UNIVERSITY',
    address: '충남 아산시 신창면 순천향로 22',
    latitude: 36.7704,
    longitude: 126.9326,
    isMetroArea: false,
    searchKeywords: ['순천향대', 'SCH', '순천향대학교'],
  },
  {
    name: '국민대학교',
    nameEn: 'Kookmin University',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 정릉로 77',
    latitude: 37.6109,
    longitude: 126.9958,
    isMetroArea: true,
    searchKeywords: ['국민대', 'Kookmin', '국민대학교'],
  },
  {
    name: '세종대학교',
    nameEn: 'Sejong University',
    type: 'UNIVERSITY',
    address: '서울특별시 광진구 능동로 209',
    latitude: 37.5506,
    longitude: 127.0739,
    isMetroArea: true,
    searchKeywords: ['세종대', 'Sejong', '세종대학교'],
  },
  {
    name: '홍익대학교',
    nameEn: 'Hongik University',
    type: 'UNIVERSITY',
    address: '서울특별시 마포구 와우산로 94',
    latitude: 37.5511,
    longitude: 126.9254,
    isMetroArea: true,
    searchKeywords: ['홍익대', 'Hongik', '홍대', '홍익대학교'],
  },
  {
    name: '건국대학교',
    nameEn: 'Konkuk University',
    type: 'UNIVERSITY',
    address: '서울특별시 광진구 능동로 120',
    latitude: 37.5409,
    longitude: 127.0779,
    isMetroArea: true,
    searchKeywords: ['건국대', 'Konkuk', '건대', '건국대학교'],
  },
  {
    name: '동국대학교',
    nameEn: 'Dongguk University',
    type: 'UNIVERSITY',
    address: '서울특별시 중구 필동로1길 30',
    latitude: 37.5583,
    longitude: 127.0000,
    isMetroArea: true,
    searchKeywords: ['동국대', 'Dongguk', '동국대학교'],
  },
  {
    name: '숭실대학교',
    nameEn: 'Soongsil University',
    type: 'UNIVERSITY',
    address: '서울특별시 동작구 상도로 369',
    latitude: 37.4963,
    longitude: 126.9574,
    isMetroArea: true,
    searchKeywords: ['숭실대', 'SSU', 'Soongsil', '숭실대학교'],
  },

  // ===== 지방 사립대 추가 (50개) =====
  {
    name: '울산대학교',
    nameEn: 'University of Ulsan',
    type: 'UNIVERSITY',
    address: '울산광역시 남구 대학로 93',
    latitude: 35.5415,
    longitude: 129.3184,
    isMetroArea: false,
    searchKeywords: ['울산대', 'UOU', '울산대학교'],
  },
  {
    name: '경성대학교',
    nameEn: 'Kyungsung University',
    type: 'UNIVERSITY',
    address: '부산광역시 남구 수영로 309',
    latitude: 35.1367,
    longitude: 129.1024,
    isMetroArea: false,
    searchKeywords: ['경성대', 'KSU', '경성대학교'],
  },
  {
    name: '신라대학교',
    nameEn: 'Silla University',
    type: 'UNIVERSITY',
    address: '부산광역시 사상구 백양대로 700번길 140',
    latitude: 35.1504,
    longitude: 128.9711,
    isMetroArea: false,
    searchKeywords: ['신라대', 'Silla', '신라대학교'],
  },
  {
    name: '동의대학교',
    nameEn: 'Dong-eui University',
    type: 'UNIVERSITY',
    address: '부산광역시 부산진구 엄광로 176',
    latitude: 35.1458,
    longitude: 129.0447,
    isMetroArea: false,
    searchKeywords: ['동의대', 'DEU', '동의대학교'],
  },
  {
    name: '부산가톨릭대학교',
    nameEn: 'Catholic University of Pusan',
    type: 'UNIVERSITY',
    address: '부산광역시 금정구 오륜대로 57',
    latitude: 35.2300,
    longitude: 129.0924,
    isMetroArea: false,
    searchKeywords: ['부산가톨릭대', '부가대', 'CUP', '부산가톨릭대학교'],
  },
  {
    name: '부산외국어대학교',
    nameEn: 'Busan University of Foreign Studies',
    type: 'UNIVERSITY',
    address: '부산광역시 금정구 금샘로 485번길 65',
    latitude: 35.2401,
    longitude: 129.0279,
    isMetroArea: false,
    searchKeywords: ['부산외대', 'BUFS', '부산외국어대학교'],
  },
  {
    name: '동명대학교',
    nameEn: 'Tongmyong University',
    type: 'UNIVERSITY',
    address: '부산광역시 남구 신선로 428',
    latitude: 35.1358,
    longitude: 129.0841,
    isMetroArea: false,
    searchKeywords: ['동명대', 'TU', '동명대학교'],
  },
  {
    name: '경남대학교',
    nameEn: 'Kyungnam University',
    type: 'UNIVERSITY',
    address: '경남 창원시 마산합포구 경남대학로 7',
    latitude: 35.2415,
    longitude: 128.5739,
    isMetroArea: false,
    searchKeywords: ['경남대', 'KNU', '경남대학교'],
  },
  {
    name: '경남과학기술대학교',
    nameEn: 'Gyeongnam National University of Science and Technology',
    type: 'UNIVERSITY',
    address: '경남 진주시 동진로 33',
    latitude: 35.1898,
    longitude: 128.1105,
    isMetroArea: false,
    searchKeywords: ['경남과기대', 'GNTECH', '경남과학기술대학교'],
  },
  {
    name: '한국국제대학교',
    nameEn: 'International University of Korea',
    type: 'UNIVERSITY',
    address: '경남 진주시 진주대로 1714-1',
    latitude: 35.1659,
    longitude: 128.1307,
    isMetroArea: false,
    searchKeywords: ['한국국제대', 'IUK', '한국국제대학교'],
  },
  {
    name: '경일대학교',
    nameEn: 'Kyungil University',
    type: 'UNIVERSITY',
    address: '경북 경산시 하양읍 가마실길 50',
    latitude: 35.9082,
    longitude: 128.8197,
    isMetroArea: false,
    searchKeywords: ['경일대', 'KIU', '경일대학교'],
  },
  {
    name: '대구한의대학교',
    nameEn: 'Daegu Haany University',
    type: 'UNIVERSITY',
    address: '경북 경산시 한의대로 1',
    latitude: 35.8885,
    longitude: 128.8350,
    isMetroArea: false,
    searchKeywords: ['대구한의대', 'DHU', '대구한의대학교'],
  },
  {
    name: '대구대학교',
    nameEn: 'Daegu University',
    type: 'UNIVERSITY',
    address: '경북 경산시 진량읍 대구대로 201',
    latitude: 35.9059,
    longitude: 128.8093,
    isMetroArea: false,
    searchKeywords: ['대구대', 'DU', '대구대학교'],
  },
  {
    name: '경운대학교',
    nameEn: 'Kyungwoon University',
    type: 'UNIVERSITY',
    address: '경북 구미시 산동면 강동로 730',
    latitude: 36.2043,
    longitude: 128.2905,
    isMetroArea: false,
    searchKeywords: ['경운대', 'KWU', '경운대학교'],
  },
  {
    name: '위덕대학교',
    nameEn: 'Uiduk University',
    type: 'UNIVERSITY',
    address: '경북 경주시 강동면 동해대로 261',
    latitude: 35.8152,
    longitude: 129.3526,
    isMetroArea: false,
    searchKeywords: ['위덕대', 'UDU', '위덕대학교'],
  },
  {
    name: '포항공과대학교',
    nameEn: 'Pohang University of Science and Technology',
    type: 'UNIVERSITY',
    address: '경북 포항시 남구 청암로 77',
    latitude: 36.0137,
    longitude: 129.3241,
    isMetroArea: false,
    searchKeywords: ['포스텍', 'POSTECH', '포항공대', '포항공과대학교'],
  },
  {
    name: '대전대학교',
    nameEn: 'Daejeon University',
    type: 'UNIVERSITY',
    address: '대전광역시 동구 대학로 62',
    latitude: 36.3331,
    longitude: 127.4325,
    isMetroArea: false,
    searchKeywords: ['대전대', 'DJU', '대전대학교'],
  },
  {
    name: '목원대학교',
    nameEn: 'Mokwon University',
    type: 'UNIVERSITY',
    address: '대전광역시 서구 도안북로 88',
    latitude: 36.3639,
    longitude: 127.2980,
    isMetroArea: false,
    searchKeywords: ['목원대', 'MU', '목원대학교'],
  },
  {
    name: '우송대학교',
    nameEn: 'Woosong University',
    type: 'UNIVERSITY',
    address: '대전광역시 동구 동대전로 171',
    latitude: 36.3275,
    longitude: 127.4527,
    isMetroArea: false,
    searchKeywords: ['우송대', 'WSU', '우송대학교'],
  },
  {
    name: '배재대학교',
    nameEn: 'Pai Chai University',
    type: 'UNIVERSITY',
    address: '대전광역시 서구 배재로 155-40',
    latitude: 36.3142,
    longitude: 127.3510,
    isMetroArea: false,
    searchKeywords: ['배재대', 'PCU', '배재대학교'],
  },
  {
    name: '한남대학교',
    nameEn: 'Hannam University',
    type: 'UNIVERSITY',
    address: '대전광역시 대덕구 한남로 70',
    latitude: 36.3554,
    longitude: 127.4218,
    isMetroArea: false,
    searchKeywords: ['한남대', 'HNU', '한남대학교'],
  },
  {
    name: '건양대학교',
    nameEn: 'Konyang University',
    type: 'UNIVERSITY',
    address: '대전광역시 서구 관저동로 158',
    latitude: 36.3223,
    longitude: 127.3314,
    isMetroArea: false,
    searchKeywords: ['건양대', 'KYU', '건양대학교'],
  },
  {
    name: '충청대학교',
    nameEn: 'Chungcheong University',
    type: 'COLLEGE',
    address: '충북 청주시 흥덕구 강내면 월곡길 38',
    latitude: 36.6397,
    longitude: 127.2807,
    isMetroArea: false,
    searchKeywords: ['충청대', 'CCU', '충청대학교'],
  },
  {
    name: '청주대학교',
    nameEn: 'Cheongju University',
    type: 'UNIVERSITY',
    address: '충북 청주시 청원구 대성로 298',
    latitude: 36.6443,
    longitude: 127.4810,
    isMetroArea: false,
    searchKeywords: ['청주대', 'CJU', '청주대학교'],
  },
  {
    name: '서원대학교',
    nameEn: 'Seowon University',
    type: 'UNIVERSITY',
    address: '충북 청주시 흥덕구 무심서로 377-3',
    latitude: 36.6272,
    longitude: 127.4071,
    isMetroArea: false,
    searchKeywords: ['서원대', 'SWU', '서원대학교'],
  },
  {
    name: '천안대학교',
    nameEn: 'Cheonan University',
    type: 'COLLEGE',
    address: '충남 천안시 서북구 천안대로 429',
    latitude: 36.8266,
    longitude: 127.1324,
    isMetroArea: false,
    searchKeywords: ['천안대', 'CU', '천안대학교'],
  },
  {
    name: '남서울대학교',
    nameEn: 'Namseoul University',
    type: 'UNIVERSITY',
    address: '충남 천안시 서북구 성환읍 대학로 91',
    latitude: 36.8070,
    longitude: 127.0891,
    isMetroArea: false,
    searchKeywords: ['남서울대', 'NSU', '남서울대학교'],
  },
  {
    name: '호서대학교',
    nameEn: 'Hoseo University',
    type: 'UNIVERSITY',
    address: '충남 아산시 배방읍 호서로 79번길 20',
    latitude: 36.7734,
    longitude: 127.0821,
    isMetroArea: false,
    searchKeywords: ['호서대', 'HSU', '호서대학교'],
  },
  {
    name: '백석대학교',
    nameEn: 'Baekseok University',
    type: 'UNIVERSITY',
    address: '충남 천안시 동남구 백석대학로 1',
    latitude: 36.7768,
    longitude: 127.1806,
    isMetroArea: false,
    searchKeywords: ['백석대', 'BU', '백석대학교'],
  },
  {
    name: '상지대학교',
    nameEn: 'Sangji University',
    type: 'UNIVERSITY',
    address: '강원 원주시 상지대길 83',
    latitude: 37.3338,
    longitude: 127.9429,
    isMetroArea: false,
    searchKeywords: ['상지대', 'SJU', '상지대학교'],
  },
  {
    name: '한라대학교',
    nameEn: 'Halla University',
    type: 'UNIVERSITY',
    address: '강원 원주시 한라대1길 28',
    latitude: 37.3152,
    longitude: 127.9528,
    isMetroArea: false,
    searchKeywords: ['한라대', 'HU', '한라대학교'],
  },
  {
    name: '연세대학교 원주캠퍼스',
    nameEn: 'Yonsei University Wonju Campus',
    type: 'UNIVERSITY',
    address: '강원 원주시 연세대길 1',
    latitude: 37.3682,
    longitude: 127.9456,
    isMetroArea: false,
    searchKeywords: ['연세대 원주', 'Yonsei Wonju', '연세대학교 원주'],
  },
  {
    name: '관동대학교',
    nameEn: 'Kwandong University',
    type: 'UNIVERSITY',
    address: '강원 강릉시 범일로 579번길 24',
    latitude: 37.7710,
    longitude: 128.8707,
    isMetroArea: false,
    searchKeywords: ['관동대', 'KDU', '관동대학교'],
  },
  {
    name: '송원대학교',
    nameEn: 'Songwon University',
    type: 'UNIVERSITY',
    address: '광주광역시 남구 송암로 73',
    latitude: 35.1127,
    longitude: 126.8999,
    isMetroArea: false,
    searchKeywords: ['송원대', 'SWU', '송원대학교'],
  },
  {
    name: '광주여자대학교',
    nameEn: 'Kwangju Women\'s University',
    type: 'UNIVERSITY',
    address: '광주광역시 광산구 여대길 201',
    latitude: 35.1664,
    longitude: 126.8176,
    isMetroArea: false,
    searchKeywords: ['광주여대', 'KWWU', '광주여자대학교'],
  },
  {
    name: '동신대학교',
    nameEn: 'Dongshin University',
    type: 'UNIVERSITY',
    address: '전남 나주시 건재로 185',
    latitude: 35.0267,
    longitude: 126.7560,
    isMetroArea: false,
    searchKeywords: ['동신대', 'DSU', '동신대학교'],
  },
  {
    name: '남부대학교',
    nameEn: 'Nambu University',
    type: 'UNIVERSITY',
    address: '광주광역시 광산구 첨단중앙로 170',
    latitude: 35.2095,
    longitude: 126.8511,
    isMetroArea: false,
    searchKeywords: ['남부대', 'NBU', '남부대학교'],
  },
  {
    name: '세한대학교',
    nameEn: 'Sehan University',
    type: 'UNIVERSITY',
    address: '전남 영암군 삼호읍 녹색로 1113',
    latitude: 34.8318,
    longitude: 126.4563,
    isMetroArea: false,
    searchKeywords: ['세한대', 'SHU', '세한대학교'],
  },
  {
    name: '전주대학교',
    nameEn: 'Jeonju University',
    type: 'UNIVERSITY',
    address: '전북 전주시 완산구 천잠로 303',
    latitude: 35.8066,
    longitude: 127.1279,
    isMetroArea: false,
    searchKeywords: ['전주대', 'JJU', '전주대학교'],
  },
  {
    name: '우송정보대학',
    nameEn: 'Woosong University Information College',
    type: 'COLLEGE',
    address: '대전광역시 동구 우송정보대학로 171',
    latitude: 36.3275,
    longitude: 127.4527,
    isMetroArea: false,
    searchKeywords: ['우송정보대', 'WIC', '우송정보대학'],
  },
  {
    name: '한림대학교',
    nameEn: 'Hallym University',
    type: 'UNIVERSITY',
    address: '강원 춘천시 한림대학길 1',
    latitude: 37.8861,
    longitude: 127.7385,
    isMetroArea: false,
    searchKeywords: ['한림대', 'HU', '한림대학교'],
  },
  {
    name: '가야대학교',
    nameEn: 'Kaya University',
    type: 'UNIVERSITY',
    address: '경남 김해시 삼계로 208',
    latitude: 35.2187,
    longitude: 128.8905,
    isMetroArea: false,
    searchKeywords: ['가야대', 'Kaya', '가야대학교'],
  },
  {
    name: '경동대학교',
    nameEn: 'Kyungdong University',
    type: 'UNIVERSITY',
    address: '강원 고성군 토성면 동해대로 278',
    latitude: 38.3290,
    longitude: 128.4713,
    isMetroArea: false,
    searchKeywords: ['경동대', 'KDU', '경동대학교'],
  },
  {
    name: '경주대학교',
    nameEn: 'Gyeongju University',
    type: 'UNIVERSITY',
    address: '경북 경주시 동대로 123',
    latitude: 35.8150,
    longitude: 129.2020,
    isMetroArea: false,
    searchKeywords: ['경주대', 'GJU', '경주대학교'],
  },
  {
    name: '대진대학교',
    nameEn: 'Daejin University',
    type: 'UNIVERSITY',
    address: '경기도 포천시 호국로 1007',
    latitude: 37.9397,
    longitude: 127.0621,
    isMetroArea: true,
    searchKeywords: ['대진대', 'DJU', '대진대학교'],
  },
  {
    name: '루터대학교',
    nameEn: 'Luther University',
    type: 'UNIVERSITY',
    address: '경기도 용인시 기흥구 덕영대로 1555',
    latitude: 37.2351,
    longitude: 127.0821,
    isMetroArea: true,
    searchKeywords: ['루터대', 'Luther', '루터대학교'],
  },
  {
    name: '서울기독대학교',
    nameEn: 'Seoul Christian University',
    type: 'UNIVERSITY',
    address: '서울특별시 은평구 연서로 123',
    latitude: 37.6381,
    longitude: 126.9132,
    isMetroArea: true,
    searchKeywords: ['서울기독대', 'SCU', '서울기독대학교'],
  },
  {
    name: '서울신학대학교',
    nameEn: 'Seoul Theological University',
    type: 'UNIVERSITY',
    address: '경기도 부천시 소사로 101',
    latitude: 37.4847,
    longitude: 126.7899,
    isMetroArea: true,
    searchKeywords: ['서울신학대', '서신대', 'STU', '서울신학대학교'],
  },
  {
    name: '성공회대학교',
    nameEn: 'Sungkonghoe University',
    type: 'UNIVERSITY',
    address: '서울특별시 구로구 연동로 320',
    latitude: 37.4871,
    longitude: 126.9088,
    isMetroArea: true,
    searchKeywords: ['성공회대', 'SKHU', '성공회대학교'],
  },
  {
    name: 'KC대학교',
    nameEn: 'KC University',
    type: 'UNIVERSITY',
    address: '서울특별시 강서구 강서로 56길 17',
    latitude: 37.5421,
    longitude: 126.8229,
    isMetroArea: true,
    searchKeywords: ['KC대', 'KCU', 'KC대학교'],
  },
  {
    name: '추계예술대학교',
    nameEn: 'Chugye University for the Arts',
    type: 'UNIVERSITY',
    address: '서울특별시 서대문구 홍제동 330',
    latitude: 37.5825,
    longitude: 126.9507,
    isMetroArea: true,
    searchKeywords: ['추계예대', 'Chugye', '추계예술대학교'],
  },
  {
    name: '백석예술대학교',
    nameEn: 'Baekseok Arts University',
    type: 'UNIVERSITY',
    address: '서울특별시 서초구 남부순환로 2366',
    latitude: 37.4831,
    longitude: 126.9819,
    isMetroArea: true,
    searchKeywords: ['백석예대', 'BAU', '백석예술대학교'],
  },
  {
    name: '극동대학교',
    nameEn: 'Keukdong University',
    type: 'UNIVERSITY',
    address: '충북 음성군 감곡면 대학길 61',
    latitude: 36.9886,
    longitude: 127.5390,
    isMetroArea: false,
    searchKeywords: ['극동대', 'KDU', '극동대학교'],
  },
  {
    name: '중부대학교',
    nameEn: 'Joongbu University',
    type: 'UNIVERSITY',
    address: '충남 금산군 추부면 대학로 201',
    latitude: 36.1132,
    longitude: 127.4479,
    isMetroArea: false,
    searchKeywords: ['중부대', 'JU', '중부대학교'],
  },
  {
    name: '송호대학교',
    nameEn: 'Songho University',
    type: 'UNIVERSITY',
    address: '강원 횡성군 우천면 우항로 1113',
    latitude: 37.4547,
    longitude: 127.9442,
    isMetroArea: false,
    searchKeywords: ['송호대', 'SHU', '송호대학교'],
  },
  {
    name: '한라대학교',
    nameEn: 'Halla University',
    type: 'UNIVERSITY',
    address: '강원 원주시 한라대1길 28',
    latitude: 37.3152,
    longitude: 127.9528,
    isMetroArea: false,
    searchKeywords: ['한라대', 'HU', '한라대학교'],
  },
  {
    name: '청운대학교',
    nameEn: 'Chungwoon University',
    type: 'UNIVERSITY',
    address: '충남 홍성군 홍성읍 대학길 25',
    latitude: 36.5988,
    longitude: 126.6641,
    isMetroArea: false,
    searchKeywords: ['청운대', 'CU', '청운대학교'],
  },
  {
    name: '을지대학교',
    nameEn: 'Eulji University',
    type: 'UNIVERSITY',
    address: '대전광역시 중구 계룡로 771번길 77',
    latitude: 36.3391,
    longitude: 127.3978,
    isMetroArea: false,
    searchKeywords: ['을지대', 'EU', '을지대학교'],
  },
  {
    name: '대불대학교',
    nameEn: 'Daebul University',
    type: 'UNIVERSITY',
    address: '전남 영암군 삼호읍 대불주거1로 24',
    latitude: 34.8326,
    longitude: 126.4581,
    isMetroArea: false,
    searchKeywords: ['대불대', 'DBU', '대불대학교'],
  },
  {
    name: '목포해양대학교',
    nameEn: 'Mokpo National Maritime University',
    type: 'UNIVERSITY',
    address: '전남 목포시 해양대학로 91',
    latitude: 34.9150,
    longitude: 126.3825,
    isMetroArea: false,
    searchKeywords: ['목포해양대', 'MMU', '목포해양대학교'],
  },
  {
    name: '광주대학교',
    nameEn: 'Gwangju University',
    type: 'UNIVERSITY',
    address: '광주광역시 남구 효덕로 277',
    latitude: 35.1631,
    longitude: 126.8854,
    isMetroArea: false,
    searchKeywords: ['광주대', 'GU', '광주대학교'],
  },
  {
    name: '광신대학교',
    nameEn: 'Kwangshin University',
    type: 'UNIVERSITY',
    address: '광주광역시 북구 송우로 77-6',
    latitude: 35.1954,
    longitude: 126.8979,
    isMetroArea: false,
    searchKeywords: ['광신대', 'KSU', '광신대학교'],
  },
  {
    name: '서남대학교',
    nameEn: 'Seonam University',
    type: 'UNIVERSITY',
    address: '전북 남원시 광치동 1640',
    latitude: 35.4035,
    longitude: 127.3494,
    isMetroArea: false,
    searchKeywords: ['서남대', 'SNU', '서남대학교'],
  },
  {
    name: '예수대학교',
    nameEn: 'Yesu University',
    type: 'UNIVERSITY',
    address: '전북 전주시 완산구 서곡로 238',
    latitude: 35.8122,
    longitude: 127.0774,
    isMetroArea: false,
    searchKeywords: ['예수대', 'YU', '예수대학교'],
  },
  {
    name: '한일장신대학교',
    nameEn: 'Hanil University & Presbyterian Theological Seminary',
    type: 'UNIVERSITY',
    address: '전북 완주군 상관면 한일로 558',
    latitude: 35.9254,
    longitude: 127.1973,
    isMetroArea: false,
    searchKeywords: ['한일장신대', 'HUPTS', '한일장신대학교'],
  },
  {
    name: '부산장신대학교',
    nameEn: 'Busan Presbyterian University',
    type: 'UNIVERSITY',
    address: '부산광역시 금정구 금샘로 121',
    latitude: 35.2415,
    longitude: 129.0262,
    isMetroArea: false,
    searchKeywords: ['부산장신대', 'BPU', '부산장신대학교'],
  },
  {
    name: '고신대학교',
    nameEn: 'Kosin University',
    type: 'UNIVERSITY',
    address: '부산광역시 영도구 와치로 194',
    latitude: 35.0615,
    longitude: 129.0682,
    isMetroArea: false,
    searchKeywords: ['고신대', 'KU', '고신대학교'],
  },
  {
    name: '영산대학교',
    nameEn: 'Youngsan University',
    type: 'UNIVERSITY',
    address: '경남 양산시 주남로 288',
    latitude: 35.3455,
    longitude: 129.0367,
    isMetroArea: false,
    searchKeywords: ['영산대', 'YSU', '영산대학교'],
  },
  {
    name: '한국교통대학교',
    nameEn: 'Korea National University of Transportation',
    type: 'UNIVERSITY',
    address: '충북 충주시 대학로 50',
    latitude: 37.0081,
    longitude: 127.9159,
    isMetroArea: false,
    searchKeywords: ['한국교통대', '교통대', 'KNUT', '한국교통대학교'],
  },
  {
    name: '세명대학교',
    nameEn: 'Semyung University',
    type: 'UNIVERSITY',
    address: '충북 제천시 세명로 65',
    latitude: 37.1473,
    longitude: 128.2107,
    isMetroArea: false,
    searchKeywords: ['세명대', 'SMU', '세명대학교'],
  },
  {
    name: '한서대학교',
    nameEn: 'Hanseo University',
    type: 'UNIVERSITY',
    address: '충남 서산시 해미면 한서1로 46',
    latitude: 36.7421,
    longitude: 126.4641,
    isMetroArea: false,
    searchKeywords: ['한서대', 'HSU', '한서대학교'],
  },
  {
    name: '선문대학교',
    nameEn: 'Sun Moon University',
    type: 'UNIVERSITY',
    address: '충남 아산시 탕정면 선문로 221번길 70',
    latitude: 36.8008,
    longitude: 127.0743,
    isMetroArea: false,
    searchKeywords: ['선문대', 'SMU', '선문대학교'],
  },
  {
    name: '한동대학교',
    nameEn: 'Handong Global University',
    type: 'UNIVERSITY',
    address: '경북 포항시 북구 흥해읍 한동로 558',
    latitude: 36.1033,
    longitude: 129.3876,
    isMetroArea: false,
    searchKeywords: ['한동대', 'HGU', '한동대학교'],
  },
  {
    name: '영진전문대학',
    nameEn: 'Yeungjin University',
    type: 'COLLEGE',
    address: '대구광역시 북구 복현로 35',
    latitude: 35.9078,
    longitude: 128.6115,
    isMetroArea: false,
    searchKeywords: ['영진전문대', 'YJC', '영진전문대학'],
  },
  {
    name: '대구공업대학교',
    nameEn: 'Daegu Technical University',
    type: 'COLLEGE',
    address: '대구광역시 달서구 달구벌대로 1095',
    latitude: 35.8554,
    longitude: 128.4895,
    isMetroArea: false,
    searchKeywords: ['대구공업대', 'DTU', '대구공업대학교'],
  },
];

export const EXTENDED_LANGUAGE_INSTITUTES: InstitutionSeedData[] = [
  // ===== 지방 주요 어학당 (30개) =====
  {
    name: '부경대학교 한국어교육센터',
    nameEn: 'Pukyong National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 남구 용소로 45',
    addressDetail: '국제관',
    latitude: 35.1340,
    longitude: 129.1020,
    isMetroArea: false,
    affiliatedUniversity: '부경대학교',
    searchKeywords: ['부경대 한국어센터', 'PKNU KLEC'],
  },
  {
    name: '동아대학교 한국어교육센터',
    nameEn: 'Dong-A University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 사하구 낙동대로 550번길 37',
    addressDetail: '인문사회관',
    latitude: 35.1240,
    longitude: 128.9700,
    isMetroArea: false,
    affiliatedUniversity: '동아대학교',
    searchKeywords: ['동아대 한국어센터', 'DAU KLEC'],
  },
  {
    name: '영남대학교 한국어학당',
    nameEn: 'Yeungnam University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대구광역시 경산시 대학로 280',
    addressDetail: '국제교류관',
    latitude: 35.8330,
    longitude: 128.7550,
    isMetroArea: false,
    affiliatedUniversity: '영남대학교',
    searchKeywords: ['영남대 어학당', 'YU KLI'],
  },
  {
    name: '계명대학교 한국어교육센터',
    nameEn: 'Keimyung University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '대구광역시 달서구 달구벌대로 1095',
    addressDetail: '국제관',
    latitude: 35.8555,
    longitude: 128.4895,
    isMetroArea: false,
    affiliatedUniversity: '계명대학교',
    searchKeywords: ['계명대 한국어센터', 'KMU KLEC'],
  },
  {
    name: '조선대학교 한국어교육센터',
    nameEn: 'Chosun University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '광주광역시 동구 필문대로 309',
    addressDetail: '글로벌관',
    latitude: 35.1400,
    longitude: 126.9280,
    isMetroArea: false,
    affiliatedUniversity: '조선대학교',
    searchKeywords: ['조선대 한국어센터', 'Chosun KLEC'],
  },
  {
    name: '호남대학교 한국어교육원',
    nameEn: 'Honam University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '광주광역시 광산구 호남대학로 120',
    addressDetail: '국제교류관',
    latitude: 35.1765,
    longitude: 126.7308,
    isMetroArea: false,
    affiliatedUniversity: '호남대학교',
    searchKeywords: ['호남대 어학원', 'Honam KLI'],
  },
  {
    name: '충북대학교 한국어교육원',
    nameEn: 'Chungbuk National University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충북 청주시 서원구 충대로 1',
    addressDetail: '국제교류관',
    latitude: 36.6282,
    longitude: 127.4575,
    isMetroArea: false,
    affiliatedUniversity: '충북대학교',
    searchKeywords: ['충북대 한국어교육원', 'CBNU KLI'],
  },
  {
    name: '원광대학교 한국어교육센터',
    nameEn: 'Wonkwang University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '전북 익산시 익산대로 460',
    addressDetail: '국제관',
    latitude: 35.9683,
    longitude: 126.9580,
    isMetroArea: false,
    affiliatedUniversity: '원광대학교',
    searchKeywords: ['원광대 한국어센터', 'WKU KLEC'],
  },
  {
    name: '제주대학교 한국어교육센터',
    nameEn: 'Jeju National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '제주특별자치도 제주시 제주대학로 102',
    addressDetail: '인문대학',
    latitude: 33.4572,
    longitude: 126.5608,
    isMetroArea: false,
    affiliatedUniversity: '제주대학교',
    searchKeywords: ['제주대 한국어센터', 'JNU KLEC'],
  },
  {
    name: '강원대학교 한국어교육센터',
    nameEn: 'Kangwon National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '강원 춘천시 강원대학길 1',
    addressDetail: '인문대학',
    latitude: 37.8691,
    longitude: 127.7442,
    isMetroArea: false,
    affiliatedUniversity: '강원대학교',
    searchKeywords: ['강원대 한국어센터', 'KNU KLEC'],
  },
  {
    name: '경상국립대학교 한국어교육센터',
    nameEn: 'Gyeongsang National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '경남 진주시 진주대로 501',
    addressDetail: '인문대학',
    latitude: 35.1558,
    longitude: 128.0963,
    isMetroArea: false,
    affiliatedUniversity: '경상국립대학교',
    searchKeywords: ['경상대 한국어센터', 'GNU KLEC'],
  },
  {
    name: '인하대학교 한국어교육원',
    nameEn: 'Inha University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '인천광역시 미추홀구 인하로 100',
    addressDetail: '국제교류관',
    latitude: 37.4505,
    longitude: 126.6565,
    isMetroArea: true,
    affiliatedUniversity: '인하대학교',
    searchKeywords: ['인하대 어학원', 'Inha KLI'],
  },
  {
    name: '아주대학교 한국어교육센터',
    nameEn: 'Ajou University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '경기도 수원시 영통구 월드컵로 206',
    addressDetail: '국제관',
    latitude: 37.2815,
    longitude: 127.0445,
    isMetroArea: true,
    affiliatedUniversity: '아주대학교',
    searchKeywords: ['아주대 한국어센터', 'Ajou KLEC'],
  },
  {
    name: '가천대학교 한국어교육원',
    nameEn: 'Gachon University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경기도 성남시 수정구 성남대로 1342',
    addressDetail: '글로벌센터',
    latitude: 37.4507,
    longitude: 127.1285,
    isMetroArea: true,
    affiliatedUniversity: '가천대학교',
    searchKeywords: ['가천대 어학원', 'Gachon KLI'],
  },
  {
    name: '경기대학교 한국어교육센터',
    nameEn: 'Kyonggi University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '경기도 수원시 영통구 광교산로 154-42',
    addressDetail: '국제교류관',
    latitude: 37.3002,
    longitude: 127.0359,
    isMetroArea: true,
    affiliatedUniversity: '경기대학교',
    searchKeywords: ['경기대 한국어센터', 'KGU KLEC'],
  },
  {
    name: '단국대학교 한국어교육원',
    nameEn: 'Dankook University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경기도 용인시 수지구 죽전로 152',
    addressDetail: '퇴계기념중앙도서관',
    latitude: 37.3228,
    longitude: 127.1264,
    isMetroArea: true,
    affiliatedUniversity: '단국대학교',
    searchKeywords: ['단국대 어학원', 'DKU KLI'],
  },
  {
    name: '한국항공대학교 한국어교육원',
    nameEn: 'Korea Aerospace University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경기도 고양시 덕양구 화전동 항공대학로 76',
    addressDetail: '국제교류관',
    latitude: 37.6010,
    longitude: 126.8651,
    isMetroArea: true,
    affiliatedUniversity: '한국항공대학교',
    searchKeywords: ['항공대 어학원', 'KAU KLI'],
  },
  {
    name: '대구대학교 한국어교육원',
    nameEn: 'Daegu University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경북 경산시 진량읍 대구대로 201',
    addressDetail: '국제관',
    latitude: 35.9061,
    longitude: 128.8095,
    isMetroArea: false,
    affiliatedUniversity: '대구대학교',
    searchKeywords: ['대구대 어학원', 'DU KLI'],
  },
  {
    name: '대구가톨릭대학교 한국어교육센터',
    nameEn: 'Daegu Catholic University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '경북 경산시 하양읍 하양로 13-13',
    addressDetail: '국제교류관',
    latitude: 35.9068,
    longitude: 128.8191,
    isMetroArea: false,
    affiliatedUniversity: '대구가톨릭대학교',
    searchKeywords: ['대가대 한국어센터', 'DCU KLEC'],
  },
  {
    name: '울산대학교 한국어교육원',
    nameEn: 'University of Ulsan Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '울산광역시 남구 대학로 93',
    addressDetail: '국제관',
    latitude: 35.5417,
    longitude: 129.3186,
    isMetroArea: false,
    affiliatedUniversity: '울산대학교',
    searchKeywords: ['울산대 어학원', 'UOU KLI'],
  },
  {
    name: '경남대학교 한국어교육원',
    nameEn: 'Kyungnam University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경남 창원시 마산합포구 경남대학로 7',
    addressDetail: '국제교류관',
    latitude: 35.2417,
    longitude: 128.5741,
    isMetroArea: false,
    affiliatedUniversity: '경남대학교',
    searchKeywords: ['경남대 어학원', 'KNU KLI'],
  },
  {
    name: '인제대학교 한국어교육원',
    nameEn: 'Inje University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경남 김해시 인제로 197',
    addressDetail: '국제관',
    latitude: 35.2538,
    longitude: 128.8665,
    isMetroArea: false,
    affiliatedUniversity: '인제대학교',
    searchKeywords: ['인제대 어학원', 'Inje KLI'],
  },
  {
    name: '창원대학교 한국어교육센터',
    nameEn: 'Changwon National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '경남 창원시 의창구 창원대학로 20',
    addressDetail: '국제교류관',
    latitude: 35.2433,
    longitude: 128.6930,
    isMetroArea: false,
    affiliatedUniversity: '창원대학교',
    searchKeywords: ['창원대 한국어센터', 'CWNU KLEC'],
  },
  {
    name: '충남대학교 한국어교육원',
    nameEn: 'Chungnam National University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 유성구 대학로 99',
    addressDetail: '인문대학',
    latitude: 36.3668,
    longitude: 127.3449,
    isMetroArea: false,
    affiliatedUniversity: '충남대학교',
    searchKeywords: ['충남대 어학원', 'CNU KLI'],
  },
  {
    name: '한남대학교 한국어교육원',
    nameEn: 'Hannam University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 대덕구 한남로 70',
    addressDetail: '국제교류관',
    latitude: 36.3556,
    longitude: 127.4220,
    isMetroArea: false,
    affiliatedUniversity: '한남대학교',
    searchKeywords: ['한남대 어학원', 'HNU KLI'],
  },
  {
    name: '배재대학교 한국어교육원',
    nameEn: 'Pai Chai University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 서구 배재로 155-40',
    addressDetail: '국제관',
    latitude: 36.3144,
    longitude: 127.3512,
    isMetroArea: false,
    affiliatedUniversity: '배재대학교',
    searchKeywords: ['배재대 어학원', 'PCU KLI'],
  },
  {
    name: '대전대학교 한국어교육원',
    nameEn: 'Daejeon University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 동구 대학로 62',
    addressDetail: '국제교류관',
    latitude: 36.3333,
    longitude: 127.4327,
    isMetroArea: false,
    affiliatedUniversity: '대전대학교',
    searchKeywords: ['대전대 어학원', 'DJU KLI'],
  },
  {
    name: '건양대학교 한국어교육원',
    nameEn: 'Konyang University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 서구 관저동로 158',
    addressDetail: '국제교류관',
    latitude: 36.3225,
    longitude: 127.3316,
    isMetroArea: false,
    affiliatedUniversity: '건양대학교',
    searchKeywords: ['건양대 어학원', 'KYU KLI'],
  },
  {
    name: '청주대학교 한국어교육센터',
    nameEn: 'Cheongju University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '충북 청주시 청원구 대성로 298',
    addressDetail: '국제관',
    latitude: 36.6445,
    longitude: 127.4812,
    isMetroArea: false,
    affiliatedUniversity: '청주대학교',
    searchKeywords: ['청주대 한국어센터', 'CJU KLEC'],
  },
  {
    name: '순천향대학교 한국어교육원',
    nameEn: 'Soonchunhyang University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충남 아산시 신창면 순천향로 22',
    addressDetail: '국제관',
    latitude: 37.7706,
    longitude: 126.9328,
    isMetroArea: false,
    affiliatedUniversity: '순천향대학교',
    searchKeywords: ['순천향대 어학원', 'SCH KLI'],
  },
  {
    name: '호서대학교 한국어교육원',
    nameEn: 'Hoseo University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충남 아산시 배방읍 호서로 79번길 20',
    addressDetail: '국제교류관',
    latitude: 36.7736,
    longitude: 127.0823,
    isMetroArea: false,
    affiliatedUniversity: '호서대학교',
    searchKeywords: ['호서대 어학원', 'HSU KLI'],
  },
  {
    name: '백석대학교 한국어교육원',
    nameEn: 'Baekseok University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충남 천안시 동남구 백석대학로 1',
    addressDetail: '국제관',
    latitude: 36.7770,
    longitude: 127.1808,
    isMetroArea: false,
    affiliatedUniversity: '백석대학교',
    searchKeywords: ['백석대 어학원', 'BU KLI'],
  },
  {
    name: '남서울대학교 한국어교육센터',
    nameEn: 'Namseoul University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '충남 천안시 서북구 성환읍 대학로 91',
    addressDetail: '국제관',
    latitude: 36.8072,
    longitude: 127.0893,
    isMetroArea: false,
    affiliatedUniversity: '남서울대학교',
    searchKeywords: ['남서울대 한국어센터', 'NSU KLEC'],
  },
  {
    name: '전북대학교 한국어교육원',
    nameEn: 'Jeonbuk National University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '전북 전주시 덕진구 백제대로 567',
    addressDetail: '국제교류관',
    latitude: 35.8466,
    longitude: 127.1293,
    isMetroArea: false,
    affiliatedUniversity: '전북대학교',
    searchKeywords: ['전북대 어학원', 'JBNU KLI'],
  },
  {
    name: '전주대학교 한국어교육원',
    nameEn: 'Jeonju University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '전북 전주시 완산구 천잠로 303',
    addressDetail: '국제교류관',
    latitude: 35.8068,
    longitude: 127.1281,
    isMetroArea: false,
    affiliatedUniversity: '전주대학교',
    searchKeywords: ['전주대 어학원', 'JJU KLI'],
  },
  {
    name: '전남대학교 한국어교육센터',
    nameEn: 'Chonnam National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '광주광역시 북구 용봉로 77',
    addressDetail: '인문대학',
    latitude: 35.1754,
    longitude: 126.9082,
    isMetroArea: false,
    affiliatedUniversity: '전남대학교',
    searchKeywords: ['전남대 한국어센터', 'CNU KLEC'],
  },
  {
    name: '광주여자대학교 한국어교육원',
    nameEn: 'Kwangju Women\'s University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '광주광역시 광산구 여대길 201',
    addressDetail: '국제관',
    latitude: 35.1666,
    longitude: 126.8178,
    isMetroArea: false,
    affiliatedUniversity: '광주여자대학교',
    searchKeywords: ['광주여대 어학원', 'KWWU KLI'],
  },
  {
    name: '동신대학교 한국어교육원',
    nameEn: 'Dongshin University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '전남 나주시 건재로 185',
    addressDetail: '국제관',
    latitude: 35.0269,
    longitude: 126.7562,
    isMetroArea: false,
    affiliatedUniversity: '동신대학교',
    searchKeywords: ['동신대 어학원', 'DSU KLI'],
  },
  {
    name: '순천대학교 한국어교육센터',
    nameEn: 'Sunchon National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '전남 순천시 중앙로 255',
    addressDetail: '국제교류관',
    latitude: 34.9572,
    longitude: 127.5287,
    isMetroArea: false,
    affiliatedUniversity: '순천대학교',
    searchKeywords: ['순천대 한국어센터', 'SCNU KLEC'],
  },
  {
    name: '목포대학교 한국어교육센터',
    nameEn: 'Mokpo National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '전남 무안군 청계면 영산로 1666',
    addressDetail: '국제교류관',
    latitude: 34.9132,
    longitude: 126.4377,
    isMetroArea: false,
    affiliatedUniversity: '목포대학교',
    searchKeywords: ['목포대 한국어센터', 'MNU KLEC'],
  },
  {
    name: '부산대학교 한국어교육원',
    nameEn: 'Pusan National University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 금정구 부산대학로63번길 2',
    addressDetail: '국제관',
    latitude: 35.2317,
    longitude: 129.0838,
    isMetroArea: false,
    affiliatedUniversity: '부산대학교',
    searchKeywords: ['부산대 어학원', 'PNU KLI'],
  },
  {
    name: '경성대학교 한국어교육원',
    nameEn: 'Kyungsung University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 남구 수영로 309',
    addressDetail: '국제관',
    latitude: 35.1369,
    longitude: 129.1026,
    isMetroArea: false,
    affiliatedUniversity: '경성대학교',
    searchKeywords: ['경성대 어학원', 'KSU KLI'],
  },
  {
    name: '신라대학교 한국어교육원',
    nameEn: 'Silla University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 사상구 백양대로 700번길 140',
    addressDetail: '국제관',
    latitude: 35.1506,
    longitude: 128.9713,
    isMetroArea: false,
    affiliatedUniversity: '신라대학교',
    searchKeywords: ['신라대 어학원', 'Silla KLI'],
  },
  {
    name: '동의대학교 한국어교육원',
    nameEn: 'Dong-eui University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 부산진구 엄광로 176',
    addressDetail: '국제관',
    latitude: 35.1460,
    longitude: 129.0449,
    isMetroArea: false,
    affiliatedUniversity: '동의대학교',
    searchKeywords: ['동의대 어학원', 'DEU KLI'],
  },
  {
    name: '부산외국어대학교 한국어교육원',
    nameEn: 'Busan University of Foreign Studies Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 금정구 금샘로 485번길 65',
    addressDetail: '국제관',
    latitude: 35.2403,
    longitude: 129.0281,
    isMetroArea: false,
    affiliatedUniversity: '부산외국어대학교',
    searchKeywords: ['부산외대 어학원', 'BUFS KLI'],
  },
  {
    name: '경북대학교 한국어교육원',
    nameEn: 'Kyungpook National University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대구광역시 북구 대학로 80',
    addressDetail: '국제관',
    latitude: 35.8891,
    longitude: 128.6115,
    isMetroArea: false,
    affiliatedUniversity: '경북대학교',
    searchKeywords: ['경북대 어학원', 'KNU KLI'],
  },
  {
    name: '강릉원주대학교 한국어교육센터',
    nameEn: 'Gangneung-Wonju National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '강원 강릉시 죽헌길 7',
    addressDetail: '국제관',
    latitude: 37.7709,
    longitude: 128.8706,
    isMetroArea: false,
    affiliatedUniversity: '강릉원주대학교',
    searchKeywords: ['강릉원주대 한국어센터', 'GWNU KLEC'],
  },
  {
    name: '상지대학교 한국어교육원',
    nameEn: 'Sangji University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '강원 원주시 상지대길 83',
    addressDetail: '국제관',
    latitude: 37.3340,
    longitude: 127.9431,
    isMetroArea: false,
    affiliatedUniversity: '상지대학교',
    searchKeywords: ['상지대 어학원', 'SJU KLI'],
  },
  {
    name: '국민대학교 한국어교육원',
    nameEn: 'Kookmin University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 성북구 정릉로 77',
    addressDetail: '국제관',
    latitude: 37.6111,
    longitude: 126.9960,
    isMetroArea: true,
    affiliatedUniversity: '국민대학교',
    searchKeywords: ['국민대 어학원', 'Kookmin KLI'],
  },
  {
    name: '세종대학교 한국어교육원',
    nameEn: 'Sejong University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 광진구 능동로 209',
    addressDetail: '국제교류관',
    latitude: 37.5508,
    longitude: 127.0741,
    isMetroArea: true,
    affiliatedUniversity: '세종대학교',
    searchKeywords: ['세종대 어학원', 'Sejong KLI'],
  },
  {
    name: '홍익대학교 한국어교육원',
    nameEn: 'Hongik University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 마포구 와우산로 94',
    addressDetail: '국제교류관',
    latitude: 37.5513,
    longitude: 126.9256,
    isMetroArea: true,
    affiliatedUniversity: '홍익대학교',
    searchKeywords: ['홍익대 어학원', 'Hongik KLI'],
  },
  {
    name: '건국대학교 한국어교육원',
    nameEn: 'Konkuk University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 광진구 능동로 120',
    addressDetail: '국제교류관',
    latitude: 37.5411,
    longitude: 127.0781,
    isMetroArea: true,
    affiliatedUniversity: '건국대학교',
    searchKeywords: ['건국대 어학원', 'Konkuk KLI'],
  },
  {
    name: '동국대학교 한국어교육원',
    nameEn: 'Dongguk University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 중구 필동로1길 30',
    addressDetail: '국제관',
    latitude: 37.5585,
    longitude: 127.0002,
    isMetroArea: true,
    affiliatedUniversity: '동국대학교',
    searchKeywords: ['동국대 어학원', 'Dongguk KLI'],
  },
  {
    name: '숭실대학교 한국어교육원',
    nameEn: 'Soongsil University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 동작구 상도로 369',
    addressDetail: '국제관',
    latitude: 37.4965,
    longitude: 126.9576,
    isMetroArea: true,
    affiliatedUniversity: '숭실대학교',
    searchKeywords: ['숭실대 어학원', 'SSU KLI'],
  },
  {
    name: '이화여자대학교 한국어교육원',
    nameEn: 'Ewha Womans University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 서대문구 이화여대길 52',
    addressDetail: 'ECC',
    latitude: 37.5619,
    longitude: 126.9468,
    isMetroArea: true,
    affiliatedUniversity: '이화여자대학교',
    searchKeywords: ['이화여대 어학원', 'Ewha KLI'],
  },
  {
    name: '숙명여자대학교 한국어교육원',
    nameEn: 'Sookmyung Women\'s University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 용산구 청파로47길 100',
    addressDetail: '국제관',
    latitude: 37.5450,
    longitude: 126.9654,
    isMetroArea: true,
    affiliatedUniversity: '숙명여자대학교',
    searchKeywords: ['숙명여대 어학원', 'Sookmyung KLI'],
  },
  {
    name: '서울여자대학교 한국어교육원',
    nameEn: 'Seoul Women\'s University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 노원구 화랑로 621',
    addressDetail: '국제관',
    latitude: 37.6258,
    longitude: 127.0915,
    isMetroArea: true,
    affiliatedUniversity: '서울여자대학교',
    searchKeywords: ['서울여대 어학원', 'SWU KLI'],
  },
  {
    name: '가톨릭대학교 한국어교육원',
    nameEn: 'Catholic University of Korea Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경기도 부천시 원미구 지봉로 43',
    addressDetail: '국제관',
    latitude: 37.4865,
    longitude: 126.8016,
    isMetroArea: true,
    affiliatedUniversity: '가톨릭대학교',
    searchKeywords: ['가톨릭대 어학원', 'CUK KLI'],
  },
  {
    name: '한림대학교 한국어교육원',
    nameEn: 'Hallym University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '강원 춘천시 한림대학길 1',
    addressDetail: '국제관',
    latitude: 37.8863,
    longitude: 127.7387,
    isMetroArea: false,
    affiliatedUniversity: '한림대학교',
    searchKeywords: ['한림대 어학원', 'HU KLI'],
  },
  {
    name: '한동대학교 한국어교육원',
    nameEn: 'Handong Global University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경북 포항시 북구 흥해읍 한동로 558',
    addressDetail: '국제관',
    latitude: 36.1035,
    longitude: 129.3878,
    isMetroArea: false,
    affiliatedUniversity: '한동대학교',
    searchKeywords: ['한동대 어학원', 'HGU KLI'],
  },
  {
    name: '선문대학교 한국어교육원',
    nameEn: 'Sun Moon University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충남 아산시 탕정면 선문로 221번길 70',
    addressDetail: '국제관',
    latitude: 36.8010,
    longitude: 127.0745,
    isMetroArea: false,
    affiliatedUniversity: '선문대학교',
    searchKeywords: ['선문대 어학원', 'SMU KLI'],
  },
  {
    name: '한서대학교 한국어교육원',
    nameEn: 'Hanseo University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충남 서산시 해미면 한서1로 46',
    addressDetail: '국제관',
    latitude: 36.7423,
    longitude: 126.4643,
    isMetroArea: false,
    affiliatedUniversity: '한서대학교',
    searchKeywords: ['한서대 어학원', 'HSU KLI'],
  },
  {
    name: '세명대학교 한국어교육원',
    nameEn: 'Semyung University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충북 제천시 세명로 65',
    addressDetail: '국제관',
    latitude: 37.1475,
    longitude: 128.2109,
    isMetroArea: false,
    affiliatedUniversity: '세명대학교',
    searchKeywords: ['세명대 어학원', 'SMU KLI'],
  },
  {
    name: '한국교통대학교 한국어교육원',
    nameEn: 'Korea National University of Transportation Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '충북 충주시 대학로 50',
    addressDetail: '국제관',
    latitude: 36.0083,
    longitude: 127.9161,
    isMetroArea: false,
    affiliatedUniversity: '한국교통대학교',
    searchKeywords: ['교통대 어학원', 'KNUT KLI'],
  },
  {
    name: '광주대학교 한국어교육원',
    nameEn: 'Gwangju University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '광주광역시 남구 효덕로 277',
    addressDetail: '국제관',
    latitude: 35.1633,
    longitude: 126.8856,
    isMetroArea: false,
    affiliatedUniversity: '광주대학교',
    searchKeywords: ['광주대 어학원', 'GU KLI'],
  },
  {
    name: '군산대학교 한국어교육센터',
    nameEn: 'Kunsan National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '전북 군산시 대학로 558',
    addressDetail: '국제관',
    latitude: 35.9467,
    longitude: 126.7054,
    isMetroArea: false,
    affiliatedUniversity: '군산대학교',
    searchKeywords: ['군산대 한국어센터', 'KNU KLEC'],
  },
  {
    name: '가야대학교 한국어교육원',
    nameEn: 'Kaya University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경남 김해시 삼계로 208',
    addressDetail: '국제관',
    latitude: 35.2189,
    longitude: 128.8907,
    isMetroArea: false,
    affiliatedUniversity: '가야대학교',
    searchKeywords: ['가야대 어학원', 'Kaya KLI'],
  },
  {
    name: '안동대학교 한국어교육원',
    nameEn: 'Andong National University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경북 안동시 경동로 1375',
    addressDetail: '국제관',
    latitude: 36.5439,
    longitude: 128.7992,
    isMetroArea: false,
    affiliatedUniversity: '안동대학교',
    searchKeywords: ['안동대 어학원', 'ANU KLI'],
  },
  {
    name: '동서대학교 한국어교육원',
    nameEn: 'Dongseo University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 사상구 주례로 47',
    addressDetail: '국제관',
    latitude: 35.1756,
    longitude: 128.9932,
    isMetroArea: false,
    affiliatedUniversity: '동서대학교',
    searchKeywords: ['동서대 어학원', 'DSU KLI'],
  },
  {
    name: '대진대학교 한국어교육원',
    nameEn: 'Daejin University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경기도 포천시 호국로 1007',
    addressDetail: '국제관',
    latitude: 37.9399,
    longitude: 127.0623,
    isMetroArea: true,
    affiliatedUniversity: '대진대학교',
    searchKeywords: ['대진대 어학원', 'DJU KLI'],
  },
  {
    name: '을지대학교 한국어교육원',
    nameEn: 'Eulji University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 중구 계룡로 771번길 77',
    addressDetail: '국제관',
    latitude: 36.3393,
    longitude: 127.3980,
    isMetroArea: false,
    affiliatedUniversity: '을지대학교',
    searchKeywords: ['을지대 어학원', 'EU KLI'],
  },
];
