/**
 * 교육기관 추가 Seed 데이터 (전문대 + 추가 대학 + 추가 어학당)
 * Additional educational institutions seed data
 */

import { InstitutionSeedData } from './educational-institutions.seed';

export const ADDITIONAL_COLLEGES: InstitutionSeedData[] = [
  // ===== 전문대학 100개 추가 =====
  {
    name: '강원관광대학교',
    nameEn: 'Kangwon Tourism College',
    type: 'COLLEGE',
    address: '강원 태백시 황지동 97-22',
    latitude: 37.1699,
    longitude: 128.9896,
    isMetroArea: false,
    searchKeywords: ['강원관광대', 'KTC'],
  },
  {
    name: '강원도립대학교',
    nameEn: 'Gangwon State University',
    type: 'COLLEGE',
    address: '강원 강릉시 난곡동 660',
    latitude: 37.7526,
    longitude: 128.9059,
    isMetroArea: false,
    searchKeywords: ['강원도립대', 'GSU'],
  },
  {
    name: '강릉영동대학교',
    nameEn: 'Gangneung Yeongdong University',
    type: 'COLLEGE',
    address: '강원 강릉시 남부로 1016',
    latitude: 37.7358,
    longitude: 128.9123,
    isMetroArea: false,
    searchKeywords: ['강릉영동대', 'GYU'],
  },
  {
    name: '경남도립거창대학',
    nameEn: 'Gyeongnam Provincial Geochang College',
    type: 'COLLEGE',
    address: '경남 거창군 거창읍 거창대학로 235',
    latitude: 35.6685,
    longitude: 127.9067,
    isMetroArea: false,
    searchKeywords: ['경남도립거창대', 'GPGC'],
  },
  {
    name: '경남도립남해대학',
    nameEn: 'Gyeongnam Provincial Namhae College',
    type: 'COLLEGE',
    address: '경남 남해군 남해읍 화전로 71',
    latitude: 34.8375,
    longitude: 127.8926,
    isMetroArea: false,
    searchKeywords: ['경남도립남해대', 'GPNC'],
  },
  {
    name: '경남정보대학교',
    nameEn: 'Kyungnam College of Information & Technology',
    type: 'COLLEGE',
    address: '부산광역시 부산진구 엄광로 45',
    latitude: 35.1653,
    longitude: 129.0523,
    isMetroArea: false,
    searchKeywords: ['경남정보대', 'KCIT'],
  },
  {
    name: '경복대학교',
    nameEn: 'Kyungbok University',
    type: 'COLLEGE',
    address: '경기도 남양주시 진접읍 경복대학로 425',
    latitude: 37.7234,
    longitude: 127.1856,
    isMetroArea: true,
    searchKeywords: ['경복대', 'KU'],
  },
  {
    name: '경북도립대학교',
    nameEn: 'Gyeongbuk Provincial College',
    type: 'COLLEGE',
    address: '경북 예천군 예천읍 도립대로 114',
    latitude: 36.6258,
    longitude: 128.4533,
    isMetroArea: false,
    searchKeywords: ['경북도립대', 'GPC'],
  },
  {
    name: '경북보건대학교',
    nameEn: 'Gyeongbuk College of Health',
    type: 'COLLEGE',
    address: '경북 김천시 혁신6로 77',
    latitude: 36.0893,
    longitude: 128.0649,
    isMetroArea: false,
    searchKeywords: ['경북보건대', 'GCH'],
  },
  {
    name: '경인여자대학교',
    nameEn: 'Kyungin Women\'s University',
    type: 'COLLEGE',
    address: '인천광역시 계양구 계양산로 63',
    latitude: 37.5437,
    longitude: 126.7366,
    isMetroArea: true,
    searchKeywords: ['경인여대', 'KWU'],
  },
  {
    name: '계명문화대학교',
    nameEn: 'Keimyung College University',
    type: 'COLLEGE',
    address: '대구광역시 남구 명덕로 104',
    latitude: 35.8404,
    longitude: 128.5859,
    isMetroArea: false,
    searchKeywords: ['계명문화대', 'KCU'],
  },
  {
    name: '광주보건대학교',
    nameEn: 'Gwangju Health University',
    type: 'COLLEGE',
    address: '광주광역시 광산구 북문대로 419번길 73',
    latitude: 35.2008,
    longitude: 126.8145,
    isMetroArea: false,
    searchKeywords: ['광주보건대', 'GHU'],
  },
  {
    name: '군장대학교',
    nameEn: 'Kunjang University College',
    type: 'COLLEGE',
    address: '전북 군산시 선은3길 155',
    latitude: 35.9679,
    longitude: 126.7365,
    isMetroArea: false,
    searchKeywords: ['군장대', 'KUC'],
  },
  {
    name: '김포대학교',
    nameEn: 'Kimpo University',
    type: 'COLLEGE',
    address: '경기도 김포시 월곶면 김포대학로 415',
    latitude: 37.6398,
    longitude: 126.6234,
    isMetroArea: true,
    searchKeywords: ['김포대', 'KPU'],
  },
  {
    name: '대경대학교',
    nameEn: 'Daekyeung University',
    type: 'COLLEGE',
    address: '경북 경산시 하양읍 대경로 65',
    latitude: 35.9132,
    longitude: 128.8254,
    isMetroArea: false,
    searchKeywords: ['대경대', 'DKU'],
  },
  {
    name: '대구과학대학교',
    nameEn: 'Daegu Science University',
    type: 'COLLEGE',
    address: '대구광역시 북구 대학로 47',
    latitude: 35.9232,
    longitude: 128.5849,
    isMetroArea: false,
    searchKeywords: ['대구과학대', 'DSU'],
  },
  {
    name: '대구보건대학교',
    nameEn: 'Daegu Health College',
    type: 'COLLEGE',
    address: '대구광역시 북구 영송로 15',
    latitude: 35.9073,
    longitude: 128.5976,
    isMetroArea: false,
    searchKeywords: ['대구보건대', 'DHC'],
  },
  {
    name: '대원대학교',
    nameEn: 'Daewon University College',
    type: 'COLLEGE',
    address: '충북 제천시 신월동 산22-22',
    latitude: 37.1259,
    longitude: 128.1785,
    isMetroArea: false,
    searchKeywords: ['대원대', 'DUC'],
  },
  {
    name: '대전과학기술대학교',
    nameEn: 'Daejeon Institute of Science and Technology',
    type: 'COLLEGE',
    address: '대전광역시 유성구 가정북로 100',
    latitude: 36.3772,
    longitude: 127.3606,
    isMetroArea: false,
    searchKeywords: ['대전과학기술대', 'DIST'],
  },
  {
    name: '대전보건대학교',
    nameEn: 'Daejeon Health Institute of Technology',
    type: 'COLLEGE',
    address: '대전광역시 동구 충정로 21',
    latitude: 36.3492,
    longitude: 127.4475,
    isMetroArea: false,
    searchKeywords: ['대전보건대', 'DHIT'],
  },
  {
    name: '동강대학교',
    nameEn: 'Dongkang College',
    type: 'COLLEGE',
    address: '광주광역시 북구 동문대로 50',
    latitude: 35.1939,
    longitude: 126.9134,
    isMetroArea: false,
    searchKeywords: ['동강대', 'DC'],
  },
  {
    name: '동남보건대학교',
    nameEn: 'Dongnam Health University',
    type: 'COLLEGE',
    address: '경기도 수원시 장안구 천천로 74번길 50',
    latitude: 37.3052,
    longitude: 127.0089,
    isMetroArea: true,
    searchKeywords: ['동남보건대', 'DHU'],
  },
  {
    name: '동아인재대학교',
    nameEn: 'Donga-inchae University',
    type: 'COLLEGE',
    address: '경기도 남양주시 와부읍 덕소로 76',
    latitude: 37.5829,
    longitude: 127.1987,
    isMetroArea: true,
    searchKeywords: ['동아인재대', 'DIU'],
  },
  {
    name: '동원대학교',
    nameEn: 'Dongwon University College',
    type: 'COLLEGE',
    address: '경북 구미시 송정대로 97',
    latitude: 36.1651,
    longitude: 128.3476,
    isMetroArea: false,
    searchKeywords: ['동원대', 'DUC'],
  },
  {
    name: '동의과학대학교',
    nameEn: 'Dongeui Institute of Technology',
    type: 'COLLEGE',
    address: '부산광역시 부산진구 양지로 54',
    latitude: 35.1625,
    longitude: 129.0531,
    isMetroArea: false,
    searchKeywords: ['동의과학대', 'DIT'],
  },
  {
    name: '마산대학교',
    nameEn: 'Masan University',
    type: 'COLLEGE',
    address: '경남 창원시 의창구 사화로 640',
    latitude: 35.2615,
    longitude: 128.5862,
    isMetroArea: false,
    searchKeywords: ['마산대', 'MU'],
  },
  {
    name: '목포과학대학교',
    nameEn: 'Mokpo Science University',
    type: 'COLLEGE',
    address: '전남 무안군 청계면 영산로 1666-113',
    latitude: 34.9178,
    longitude: 126.4256,
    isMetroArea: false,
    searchKeywords: ['목포과학대', 'MSU'],
  },
  {
    name: '배화여자대학교',
    nameEn: 'Baewha Women\'s University',
    type: 'COLLEGE',
    address: '서울특별시 종로구 필운대로 1길 34',
    latitude: 37.5795,
    longitude: 126.9708,
    isMetroArea: true,
    searchKeywords: ['배화여대', 'BWU'],
  },
  {
    name: '부산경상대학교',
    nameEn: 'Busan Kyungsang College',
    type: 'COLLEGE',
    address: '부산광역시 연제구 과정로 167',
    latitude: 35.1815,
    longitude: 129.0808,
    isMetroArea: false,
    searchKeywords: ['부산경상대', 'BKC'],
  },
  {
    name: '부산과학기술대학교',
    nameEn: 'Busan Institute of Science and Technology',
    type: 'COLLEGE',
    address: '부산광역시 북구 덕천동 산93-1',
    latitude: 35.2119,
    longitude: 129.0002,
    isMetroArea: false,
    searchKeywords: ['부산과학기술대', 'BIST'],
  },
  {
    name: '부산여자대학교',
    nameEn: 'Busan Women\'s College',
    type: 'COLLEGE',
    address: '부산광역시 사상구 주례로 47',
    latitude: 35.1756,
    longitude: 128.9932,
    isMetroArea: false,
    searchKeywords: ['부산여대', 'BWC'],
  },
  {
    name: '서라벌대학교',
    nameEn: 'Sorabol College',
    type: 'COLLEGE',
    address: '경북 경주시 문무대로 2050',
    latitude: 35.8324,
    longitude: 129.2045,
    isMetroArea: false,
    searchKeywords: ['서라벌대', 'SC'],
  },
  {
    name: '서영대학교',
    nameEn: 'Seoyeong University',
    type: 'COLLEGE',
    address: '경북 영주시 순흥면 죽계로 1268',
    latitude: 36.9231,
    longitude: 128.5689,
    isMetroArea: false,
    searchKeywords: ['서영대', 'SU'],
  },
  {
    name: '서울예술대학교',
    nameEn: 'Seoul Institute of the Arts',
    type: 'COLLEGE',
    address: '경기도 안산시 단원구 예술대학로 171',
    latitude: 37.3262,
    longitude: 126.8209,
    isMetroArea: true,
    searchKeywords: ['서울예대', 'SIA'],
  },
  {
    name: '서정대학교',
    nameEn: 'Seojeong College',
    type: 'COLLEGE',
    address: '경기도 양주시 은현면 화합로 1049-56',
    latitude: 37.8454,
    longitude: 127.0452,
    isMetroArea: true,
    searchKeywords: ['서정대', 'SC'],
  },
  {
    name: '선린대학교',
    nameEn: 'Sunlin College',
    type: 'COLLEGE',
    address: '경기도 포천시 호국로 1370',
    latitude: 37.9042,
    longitude: 127.0789,
    isMetroArea: true,
    searchKeywords: ['선린대', 'SC'],
  },
  {
    name: '성덕대학교',
    nameEn: 'Sungduk College',
    type: 'COLLEGE',
    address: '경북 영천시 금노동 273',
    latitude: 35.9712,
    longitude: 128.9385,
    isMetroArea: false,
    searchKeywords: ['성덕대', 'SDC'],
  },
  {
    name: '성심외국어대학교',
    nameEn: 'Sungsim College of Foreign Languages',
    type: 'COLLEGE',
    address: '경기도 안양시 만안구 삼막로 46',
    latitude: 37.3910,
    longitude: 126.9452,
    isMetroArea: true,
    searchKeywords: ['성심외대', 'SCFL'],
  },
  {
    name: '수성대학교',
    nameEn: 'Suseong University',
    type: 'COLLEGE',
    address: '대구광역시 수성구 달구벌대로 528길 15',
    latitude: 35.8568,
    longitude: 128.6358,
    isMetroArea: false,
    searchKeywords: ['수성대', 'SU'],
  },
  {
    name: '순천제일대학교',
    nameEn: 'Suncheon Jeil College',
    type: 'COLLEGE',
    address: '전남 순천시 중앙로 255',
    latitude: 34.9570,
    longitude: 127.5285,
    isMetroArea: false,
    searchKeywords: ['순천제일대', 'SJC'],
  },
  {
    name: '신구대학교',
    nameEn: 'Shingu College',
    type: 'COLLEGE',
    address: '경기도 성남시 수정구 성남대로 1506',
    latitude: 37.4411,
    longitude: 127.1407,
    isMetroArea: true,
    searchKeywords: ['신구대', 'SC'],
  },
  {
    name: '신성대학교',
    nameEn: 'Shinsung University',
    type: 'COLLEGE',
    address: '충남 당진시 신평면 신성대학길 12',
    latitude: 36.9238,
    longitude: 126.6145,
    isMetroArea: false,
    searchKeywords: ['신성대', 'SSU'],
  },
  {
    name: '신안산대학교',
    nameEn: 'Shin Ansan University',
    type: 'COLLEGE',
    address: '경기도 안산시 단원구 신안산대학로 155',
    latitude: 37.3174,
    longitude: 126.8308,
    isMetroArea: true,
    searchKeywords: ['신안산대', 'SAU'],
  },
  {
    name: '아주자동차대학',
    nameEn: 'Ajou Motor College',
    type: 'COLLEGE',
    address: '충남 보령시 주산면 충서로 669',
    latitude: 36.3682,
    longitude: 126.5634,
    isMetroArea: false,
    searchKeywords: ['아주자동차대', 'AMC'],
  },
  {
    name: '안동과학대학교',
    nameEn: 'Andong Science College',
    type: 'COLLEGE',
    address: '경북 안동시 서동문로 189',
    latitude: 36.5689,
    longitude: 128.7245,
    isMetroArea: false,
    searchKeywords: ['안동과학대', 'ASC'],
  },
  {
    name: '안산대학교',
    nameEn: 'Ansan University',
    type: 'COLLEGE',
    address: '경기도 안산시 상록구 안산대학로 155',
    latitude: 37.3201,
    longitude: 126.8511,
    isMetroArea: true,
    searchKeywords: ['안산대', 'AU'],
  },
  {
    name: '여주대학교',
    nameEn: 'Yeoju Institute of Technology',
    type: 'COLLEGE',
    address: '경기도 여주시 세종로 338',
    latitude: 37.2872,
    longitude: 127.6389,
    isMetroArea: true,
    searchKeywords: ['여주대', 'YIT'],
  },
  {
    name: '연성대학교',
    nameEn: 'Yeonsung University',
    type: 'COLLEGE',
    address: '경기도 안양시 만안구 성결대학로 12',
    latitude: 37.3856,
    longitude: 126.9567,
    isMetroArea: true,
    searchKeywords: ['연성대', 'YU'],
  },
  {
    name: '연암대학교',
    nameEn: 'Yonam Institute of Technology',
    type: 'COLLEGE',
    address: '충북 청주시 흥덕구 강내면 학평로 160',
    latitude: 36.6562,
    longitude: 127.2645,
    isMetroArea: false,
    searchKeywords: ['연암대', 'YIT'],
  },
  {
    name: '영남이공대학교',
    nameEn: 'Yeungnam University College',
    type: 'COLLEGE',
    address: '대구광역시 남구 현충로 170',
    latitude: 35.8236,
    longitude: 128.6203,
    isMetroArea: false,
    searchKeywords: ['영남이공대', 'YUC'],
  },
  {
    name: '오산대학교',
    nameEn: 'Osan University',
    type: 'COLLEGE',
    address: '경기도 오산시 청학로 45',
    latitude: 37.1568,
    longitude: 127.0689,
    isMetroArea: true,
    searchKeywords: ['오산대', 'OU'],
  },
  {
    name: '용인송담대학교',
    nameEn: 'Yongin Songdam College',
    type: 'COLLEGE',
    address: '경기도 용인시 처인구 경안천로 73',
    latitude: 37.2145,
    longitude: 127.1823,
    isMetroArea: true,
    searchKeywords: ['용인송담대', 'YSC'],
  },
  {
    name: '울산과학대학교',
    nameEn: 'Ulsan College',
    type: 'COLLEGE',
    address: '울산광역시 동구 봉수로 101',
    latitude: 35.5226,
    longitude: 129.3584,
    isMetroArea: false,
    searchKeywords: ['울산과학대', 'UC'],
  },
  {
    name: '원광보건대학교',
    nameEn: 'Wonkwang Health Science University',
    type: 'COLLEGE',
    address: '전북 익산시 무왕로 514',
    latitude: 35.9432,
    longitude: 126.9689,
    isMetroArea: false,
    searchKeywords: ['원광보건대', 'WHSU'],
  },
  {
    name: '유한대학교',
    nameEn: 'Yuhan University',
    type: 'COLLEGE',
    address: '경기도 부천시 소사로 590',
    latitude: 37.5041,
    longitude: 126.7524,
    isMetroArea: true,
    searchKeywords: ['유한대', 'YU'],
  },
  {
    name: '인덕대학교',
    nameEn: 'Induk University',
    type: 'COLLEGE',
    address: '서울특별시 노원구 초안산로 12',
    latitude: 37.6458,
    longitude: 127.0571,
    isMetroArea: true,
    searchKeywords: ['인덕대', 'IU'],
  },
  {
    name: '인천재능대학교',
    nameEn: 'Incheon Jaeneung University',
    type: 'COLLEGE',
    address: '인천광역시 동구 재능로 178',
    latitude: 37.4821,
    longitude: 126.6523,
    isMetroArea: true,
    searchKeywords: ['인천재능대', 'IJU'],
  },
  {
    name: '전남과학대학교',
    nameEn: 'Jeonnam State University',
    type: 'COLLEGE',
    address: '전남 곡성군 옥과면 대학로 113',
    latitude: 35.2856,
    longitude: 127.2645,
    isMetroArea: false,
    searchKeywords: ['전남과학대', 'JSU'],
  },
  {
    name: '전남도립대학교',
    nameEn: 'Jeonnam Provincial University',
    type: 'COLLEGE',
    address: '전남 담양군 담양읍 죽녹원로 152',
    latitude: 35.3189,
    longitude: 126.9876,
    isMetroArea: false,
    searchKeywords: ['전남도립대', 'JPU'],
  },
  {
    name: '전북과학대학교',
    nameEn: 'Jeonbuk Science College',
    type: 'COLLEGE',
    address: '전북 정읍시 연지길 90',
    latitude: 35.5823,
    longitude: 126.8456,
    isMetroArea: false,
    searchKeywords: ['전북과학대', 'JSC'],
  },
  {
    name: '제주관광대학교',
    nameEn: 'Jeju Tourism College',
    type: 'COLLEGE',
    address: '제주특별자치도 제주시 516로 3288',
    latitude: 33.4125,
    longitude: 126.4892,
    isMetroArea: false,
    searchKeywords: ['제주관광대', 'JTC'],
  },
  {
    name: '제주한라대학교',
    nameEn: 'Cheju Halla University',
    type: 'COLLEGE',
    address: '제주특별자치도 제주시 한라대학로 38',
    latitude: 33.4856,
    longitude: 126.5134,
    isMetroArea: false,
    searchKeywords: ['제주한라대', 'CHU'],
  },
  {
    name: '조선간호대학교',
    nameEn: 'Chosun Nursing College',
    type: 'COLLEGE',
    address: '광주광역시 동구 필문대로 309',
    latitude: 35.1395,
    longitude: 126.9277,
    isMetroArea: false,
    searchKeywords: ['조선간호대', 'CNC'],
  },
  {
    name: '조선이공대학교',
    nameEn: 'Chosun College of Science & Technology',
    type: 'COLLEGE',
    address: '광주광역시 동구 필문대로 309',
    latitude: 35.1395,
    longitude: 126.9277,
    isMetroArea: false,
    searchKeywords: ['조선이공대', 'CCST'],
  },
  {
    name: '진주보건대학교',
    nameEn: 'Jinju Health College',
    type: 'COLLEGE',
    address: '경남 진주시 의병로 51',
    latitude: 35.1625,
    longitude: 128.0845,
    isMetroArea: false,
    searchKeywords: ['진주보건대', 'JHC'],
  },
  {
    name: '청강문화산업대학교',
    nameEn: 'ChungKang College of Cultural Industries',
    type: 'COLLEGE',
    address: '경기도 이천시 마장면 청강가창로 389-94',
    latitude: 37.2345,
    longitude: 127.3789,
    isMetroArea: true,
    searchKeywords: ['청강문화산업대', 'CCCI'],
  },
  {
    name: '춘해보건대학교',
    nameEn: 'Chunhae College of Health Sciences',
    type: 'COLLEGE',
    address: '울산광역시 울주군 웅촌면 대학길 9',
    latitude: 35.5134,
    longitude: 129.1845,
    isMetroArea: false,
    searchKeywords: ['춘해보건대', 'CCHS'],
  },
  {
    name: '충남도립대학교',
    nameEn: 'Chungnam State University',
    type: 'COLLEGE',
    address: '충남 논산시 연무읍 충남도립대학길 204',
    latitude: 36.1945,
    longitude: 127.1267,
    isMetroArea: false,
    searchKeywords: ['충남도립대', 'CSU'],
  },
  {
    name: '충북도립대학교',
    nameEn: 'Chungbuk Provincial University',
    type: 'COLLEGE',
    address: '충북 옥천군 옥천읍 금구로 98',
    latitude: 36.3012,
    longitude: 127.5723,
    isMetroArea: false,
    searchKeywords: ['충북도립대', 'CPU'],
  },
  {
    name: '충북보건과학대학교',
    nameEn: 'Chungbuk Health & Science University',
    type: 'COLLEGE',
    address: '충북 청주시 흥덕구 강내면 청강로 462',
    latitude: 36.6523,
    longitude: 127.2789,
    isMetroArea: false,
    searchKeywords: ['충북보건과학대', 'CHSU'],
  },
  {
    name: '한국관광대학교',
    nameEn: 'Korea Tourism College',
    type: 'COLLEGE',
    address: '충북 제천시 백운면 금표1길 85',
    latitude: 37.0645,
    longitude: 128.1234,
    isMetroArea: false,
    searchKeywords: ['한국관광대', 'KTC'],
  },
  {
    name: '한국복지대학교',
    nameEn: 'Korea Welfare University',
    type: 'COLLEGE',
    address: '경기도 평택시 용이동 산60',
    latitude: 36.9856,
    longitude: 127.0523,
    isMetroArea: true,
    searchKeywords: ['한국복지대', 'KWU'],
  },
  {
    name: '한림성심대학교',
    nameEn: 'Hallym Polytechnic University',
    type: 'COLLEGE',
    address: '강원 춘천시 한림성심길 46',
    latitude: 37.8456,
    longitude: 127.7234,
    isMetroArea: false,
    searchKeywords: ['한림성심대', 'HPU'],
  },
  {
    name: '혜전대학교',
    nameEn: 'Hyejeon College',
    type: 'COLLEGE',
    address: '충남 홍성군 홍성읍 대학길 25',
    latitude: 36.5988,
    longitude: 126.6641,
    isMetroArea: false,
    searchKeywords: ['혜전대', 'HC'],
  },
  {
    name: '호산대학교',
    nameEn: 'Hosan University',
    type: 'COLLEGE',
    address: '경남 김해시 삼계로 426',
    latitude: 35.2234,
    longitude: 128.8956,
    isMetroArea: false,
    searchKeywords: ['호산대', 'HU'],
  },
];

export const ADDITIONAL_UNIVERSITIES: InstitutionSeedData[] = [
  {
    name: '동서대학교',
    nameEn: 'Dongseo University',
    type: 'UNIVERSITY',
    address: '부산광역시 사상구 주례로 47',
    latitude: 35.1756,
    longitude: 128.9932,
    isMetroArea: false,
    searchKeywords: ['동서대', 'DSU', '동서대학교'],
  },
  {
    name: '고려대학교 세종캠퍼스',
    nameEn: 'Korea University Sejong Campus',
    type: 'UNIVERSITY',
    address: '세종특별자치시 연기면 세종로 2511',
    latitude: 36.6150,
    longitude: 127.2870,
    isMetroArea: false,
    searchKeywords: ['고려대 세종', 'KU Sejong', '고대 세종'],
  },
  {
    name: '김천대학교',
    nameEn: 'Gimcheon University',
    type: 'UNIVERSITY',
    address: '경북 김천시 대학로 214',
    latitude: 36.1184,
    longitude: 128.0878,
    isMetroArea: false,
    searchKeywords: ['김천대', 'GU', '김천대학교'],
  },
  {
    name: '창신대학교',
    nameEn: 'Changshin University',
    type: 'UNIVERSITY',
    address: '경남 창원시 마산회원구 팔용로 262',
    latitude: 35.2256,
    longitude: 128.5623,
    isMetroArea: false,
    searchKeywords: ['창신대', 'CSU', '창신대학교'],
  },
  {
    name: '호원대학교',
    nameEn: 'Howon University',
    type: 'UNIVERSITY',
    address: '전북 군산시 임피면 호원대3길 64',
    latitude: 35.9234,
    longitude: 126.7856,
    isMetroArea: false,
    searchKeywords: ['호원대', 'HU', '호원대학교'],
  },
];

export const ADDITIONAL_LANGUAGE_INSTITUTES: InstitutionSeedData[] = [
  {
    name: '한동대학교 한국어교육원',
    nameEn: 'Handong Global University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경북 포항시 북구 흥해읍 한동로 558',
    addressDetail: '국제관',
    latitude: 36.1035,
    longitude: 129.3878,
    isMetroArea: false,
    affiliatedUniversity: '한동대학교',
    searchKeywords: ['한동대 어학원', 'HGU KLI'],
  },
  {
    name: '동서대학교 한국어교육원',
    nameEn: 'Dongseo University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 사상구 주례로 47',
    addressDetail: '국제관',
    latitude: 35.1758,
    longitude: 128.9934,
    isMetroArea: false,
    affiliatedUniversity: '동서대학교',
    searchKeywords: ['동서대 어학원', 'DSU KLI'],
  },
  {
    name: '고려대학교 세종캠퍼스 한국어교육원',
    nameEn: 'Korea University Sejong Campus Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '세종특별자치시 연기면 세종로 2511',
    addressDetail: '국제관',
    latitude: 36.6152,
    longitude: 127.2872,
    isMetroArea: false,
    affiliatedUniversity: '고려대학교 세종캠퍼스',
    searchKeywords: ['고려대 세종 어학원', 'KU Sejong KLI'],
  },
  {
    name: '김천대학교 한국어교육원',
    nameEn: 'Gimcheon University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '경북 김천시 대학로 214',
    addressDetail: '국제관',
    latitude: 36.1186,
    longitude: 128.0880,
    isMetroArea: false,
    affiliatedUniversity: '김천대학교',
    searchKeywords: ['김천대 어학원', 'GU KLI'],
  },
];
