/**
 * 교육기관 Seed 데이터 / Educational institutions seed data
 *
 * 주요 대학교 + 어학당 목록
 * Major universities + language institutes list
 *
 * D-2, D-4 비자의 거리 제한 검증에 사용
 * Used for distance restriction validation for D-2, D-4 visas
 */

export interface InstitutionSeedData {
  name: string;
  nameEn?: string;
  type: 'UNIVERSITY' | 'COLLEGE' | 'GRADUATE_SCHOOL' | 'LANGUAGE_INSTITUTE' | 'VOCATIONAL_SCHOOL';
  address: string;
  addressDetail?: string;
  latitude: number;
  longitude: number;
  isMetroArea: boolean;
  affiliatedUniversity?: string;
  searchKeywords: string[];
}

export const EDUCATIONAL_INSTITUTIONS: InstitutionSeedData[] = [
  // ===== 서울권 주요 대학교 =====
  {
    name: '서울대학교',
    nameEn: 'Seoul National University',
    type: 'UNIVERSITY',
    address: '서울특별시 관악구 관악로 1',
    latitude: 37.4601,
    longitude: 126.9520,
    isMetroArea: true,
    searchKeywords: ['서울대', 'SNU', '서울대학교', 'Seoul National University'],
  },
  {
    name: '연세대학교',
    nameEn: 'Yonsei University',
    type: 'UNIVERSITY',
    address: '서울특별시 서대문구 연세로 50',
    latitude: 37.5665,
    longitude: 126.9388,
    isMetroArea: true,
    searchKeywords: ['연세대', '연대', 'Yonsei', '연세대학교'],
  },
  {
    name: '고려대학교',
    nameEn: 'Korea University',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 안암로 145',
    latitude: 37.5853,
    longitude: 127.0288,
    isMetroArea: true,
    searchKeywords: ['고려대', '고대', 'KU', 'Korea University', '고려대학교'],
  },
  {
    name: '이화여자대학교',
    nameEn: 'Ewha Womans University',
    type: 'UNIVERSITY',
    address: '서울특별시 서대문구 이화여대길 52',
    latitude: 37.5632,
    longitude: 126.9465,
    isMetroArea: true,
    searchKeywords: ['이화여대', '이대', 'Ewha', '이화여자대학교'],
  },
  {
    name: '서강대학교',
    nameEn: 'Sogang University',
    type: 'UNIVERSITY',
    address: '서울특별시 마포구 백범로 35',
    latitude: 37.5509,
    longitude: 126.9405,
    isMetroArea: true,
    searchKeywords: ['서강대', 'Sogang', '서강대학교'],
  },
  {
    name: '성균관대학교',
    nameEn: 'Sungkyunkwan University',
    type: 'UNIVERSITY',
    address: '서울특별시 종로구 성균관로 25-2',
    latitude: 37.5878,
    longitude: 126.9937,
    isMetroArea: true,
    searchKeywords: ['성균관대', '성대', 'SKKU', 'Sungkyunkwan', '성균관대학교'],
  },
  {
    name: '한양대학교',
    nameEn: 'Hanyang University',
    type: 'UNIVERSITY',
    address: '서울특별시 성동구 왕십리로 222',
    latitude: 37.5551,
    longitude: 127.0465,
    isMetroArea: true,
    searchKeywords: ['한양대', 'Hanyang', '한양대학교'],
  },
  {
    name: '경희대학교',
    nameEn: 'Kyung Hee University',
    type: 'UNIVERSITY',
    address: '서울특별시 동대문구 경희대로 26',
    latitude: 37.5971,
    longitude: 127.0513,
    isMetroArea: true,
    searchKeywords: ['경희대', 'KHU', 'Kyung Hee', '경희대학교'],
  },
  {
    name: '중앙대학교',
    nameEn: 'Chung-Ang University',
    type: 'UNIVERSITY',
    address: '서울특별시 동작구 흑석로 84',
    latitude: 37.5048,
    longitude: 126.9573,
    isMetroArea: true,
    searchKeywords: ['중앙대', 'CAU', 'Chung-Ang', '중앙대학교'],
  },
  {
    name: '건국대학교',
    nameEn: 'Konkuk University',
    type: 'UNIVERSITY',
    address: '서울특별시 광진구 능동로 120',
    latitude: 37.5410,
    longitude: 127.0785,
    isMetroArea: true,
    searchKeywords: ['건국대', 'Konkuk', '건국대학교'],
  },
  {
    name: '동국대학교',
    nameEn: 'Dongguk University',
    type: 'UNIVERSITY',
    address: '서울특별시 중구 필동로 1길 30',
    latitude: 37.5585,
    longitude: 127.0009,
    isMetroArea: true,
    searchKeywords: ['동국대', 'Dongguk', '동국대학교'],
  },
  {
    name: '홍익대학교',
    nameEn: 'Hongik University',
    type: 'UNIVERSITY',
    address: '서울특별시 마포구 와우산로 94',
    latitude: 37.5512,
    longitude: 126.9257,
    isMetroArea: true,
    searchKeywords: ['홍익대', '홍대', 'Hongik', '홍익대학교'],
  },
  {
    name: '숙명여자대학교',
    nameEn: 'Sookmyung Women\'s University',
    type: 'UNIVERSITY',
    address: '서울특별시 용산구 청파로47길 100',
    latitude: 37.5451,
    longitude: 126.9648,
    isMetroArea: true,
    searchKeywords: ['숙명여대', '숙대', 'Sookmyung', '숙명여자대학교'],
  },
  {
    name: '서울여자대학교',
    nameEn: 'Seoul Women\'s University',
    type: 'UNIVERSITY',
    address: '서울특별시 노원구 화랑로 621',
    latitude: 37.6251,
    longitude: 127.0897,
    isMetroArea: true,
    searchKeywords: ['서울여대', 'SWU', '서울여자대학교'],
  },
  {
    name: '국민대학교',
    nameEn: 'Kookmin University',
    type: 'UNIVERSITY',
    address: '서울특별시 성북구 정릉로 77',
    latitude: 37.6110,
    longitude: 126.9965,
    isMetroArea: true,
    searchKeywords: ['국민대', 'Kookmin', '국민대학교'],
  },
  {
    name: '세종대학교',
    nameEn: 'Sejong University',
    type: 'UNIVERSITY',
    address: '서울특별시 광진구 능동로 209',
    latitude: 37.5508,
    longitude: 127.0738,
    isMetroArea: true,
    searchKeywords: ['세종대', 'Sejong', '세종대학교'],
  },
  {
    name: '단국대학교',
    nameEn: 'Dankook University',
    type: 'UNIVERSITY',
    address: '경기도 용인시 수지구 죽전로 152',
    latitude: 37.3228,
    longitude: 127.1264,
    isMetroArea: true,
    searchKeywords: ['단국대', 'Dankook', '단국대학교'],
  },
  {
    name: '아주대학교',
    nameEn: 'Ajou University',
    type: 'UNIVERSITY',
    address: '경기도 수원시 영통구 월드컵로 206',
    latitude: 37.2816,
    longitude: 127.0450,
    isMetroArea: true,
    searchKeywords: ['아주대', 'Ajou', '아주대학교'],
  },
  {
    name: '가톨릭대학교',
    nameEn: 'Catholic University of Korea',
    type: 'UNIVERSITY',
    address: '경기도 부천시 원미구 지봉로 43',
    latitude: 37.4871,
    longitude: 126.8018,
    isMetroArea: true,
    searchKeywords: ['가톨릭대', 'CUK', '가톨릭대학교'],
  },
  {
    name: '인하대학교',
    nameEn: 'Inha University',
    type: 'UNIVERSITY',
    address: '인천광역시 미추홀구 인하로 100',
    latitude: 37.4506,
    longitude: 126.6559,
    isMetroArea: true,
    searchKeywords: ['인하대', 'Inha', '인하대학교'],
  },

  // ===== 지방 주요 대학교 =====
  {
    name: '부산대학교',
    nameEn: 'Pusan National University',
    type: 'UNIVERSITY',
    address: '부산광역시 금정구 부산대학로 63번길 2',
    latitude: 35.2321,
    longitude: 129.0820,
    isMetroArea: false,
    searchKeywords: ['부산대', 'PNU', '부산대학교'],
  },
  {
    name: '경북대학교',
    nameEn: 'Kyungpook National University',
    type: 'UNIVERSITY',
    address: '대구광역시 북구 대학로 80',
    latitude: 35.8900,
    longitude: 128.6103,
    isMetroArea: false,
    searchKeywords: ['경북대', 'KNU', '경북대학교'],
  },
  {
    name: '전남대학교',
    nameEn: 'Chonnam National University',
    type: 'UNIVERSITY',
    address: '광주광역시 북구 용봉로 77',
    latitude: 35.1749,
    longitude: 126.9097,
    isMetroArea: false,
    searchKeywords: ['전남대', 'CNU', '전남대학교'],
  },
  {
    name: '충남대학교',
    nameEn: 'Chungnam National University',
    type: 'UNIVERSITY',
    address: '대전광역시 유성구 대학로 99',
    latitude: 36.3683,
    longitude: 127.3448,
    isMetroArea: false,
    searchKeywords: ['충남대', 'CNU', '충남대학교'],
  },
  {
    name: '전북대학교',
    nameEn: 'Jeonbuk National University',
    type: 'UNIVERSITY',
    address: '전북 전주시 덕진구 백제대로 567',
    latitude: 35.8469,
    longitude: 127.1292,
    isMetroArea: false,
    searchKeywords: ['전북대', 'JBNU', '전북대학교'],
  },
  {
    name: '강원대학교',
    nameEn: 'Kangwon National University',
    type: 'UNIVERSITY',
    address: '강원 춘천시 강원대학길 1',
    latitude: 37.8688,
    longitude: 127.7439,
    isMetroArea: false,
    searchKeywords: ['강원대', 'KNU', '강원대학교'],
  },

  // ===== 이공계 특화 대학 =====
  {
    name: 'KAIST',
    nameEn: 'Korea Advanced Institute of Science and Technology',
    type: 'UNIVERSITY',
    address: '대전광역시 유성구 대학로 291',
    latitude: 36.3717,
    longitude: 127.3625,
    isMetroArea: false,
    searchKeywords: ['KAIST', '카이스트', '한국과학기술원'],
  },
  {
    name: 'POSTECH',
    nameEn: 'Pohang University of Science and Technology',
    type: 'UNIVERSITY',
    address: '경북 포항시 남구 청암로 77',
    latitude: 36.0143,
    longitude: 129.3242,
    isMetroArea: false,
    searchKeywords: ['POSTECH', '포스텍', '포항공과대학교'],
  },
  {
    name: 'GIST',
    nameEn: 'Gwangju Institute of Science and Technology',
    type: 'UNIVERSITY',
    address: '광주광역시 북구 첨단과기로 123',
    latitude: 35.2279,
    longitude: 126.8407,
    isMetroArea: false,
    searchKeywords: ['GIST', '지스트', '광주과학기술원'],
  },
  {
    name: 'UNIST',
    nameEn: 'Ulsan National Institute of Science and Technology',
    type: 'UNIVERSITY',
    address: '울산광역시 울주군 유니스트길 50',
    latitude: 35.5716,
    longitude: 129.1903,
    isMetroArea: false,
    searchKeywords: ['UNIST', '유니스트', '울산과학기술원'],
  },

  // ===== 서울권 주요 어학당 =====
  {
    name: '서울대학교 언어교육원',
    nameEn: 'SNU Language Education Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 관악구 관악로 1',
    addressDetail: '140동',
    latitude: 37.4603,
    longitude: 126.9515,
    isMetroArea: true,
    affiliatedUniversity: '서울대학교',
    searchKeywords: ['서울대 언어교육원', '서울대 어학당', 'SNU LEI', 'SNU 언어교육원'],
  },
  {
    name: '연세대학교 한국어학당',
    nameEn: 'Yonsei University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 서대문구 연세로 50',
    addressDetail: '외솔관',
    latitude: 37.5670,
    longitude: 126.9390,
    isMetroArea: true,
    affiliatedUniversity: '연세대학교',
    searchKeywords: ['연세대 한국어학당', '연세 KLI', 'Yonsei KLI'],
  },
  {
    name: '고려대학교 한국어문화교육센터',
    nameEn: 'Korea University Korean Language and Culture Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 성북구 안암로 145',
    addressDetail: '국제관',
    latitude: 37.5858,
    longitude: 127.0295,
    isMetroArea: true,
    affiliatedUniversity: '고려대학교',
    searchKeywords: ['고려대 한국어센터', '고려대 어학당', 'KU KLCC'],
  },
  {
    name: '이화여자대학교 언어교육원',
    nameEn: 'Ewha Language Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 서대문구 이화여대길 52',
    addressDetail: '언어교육원',
    latitude: 37.5638,
    longitude: 126.9468,
    isMetroArea: true,
    affiliatedUniversity: '이화여자대학교',
    searchKeywords: ['이화여대 언어교육원', '이대 어학당', 'Ewha Language Center'],
  },
  {
    name: '서강대학교 한국어교육원',
    nameEn: 'Sogang University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 마포구 백범로 35',
    addressDetail: '곤자가국제학사',
    latitude: 37.5512,
    longitude: 126.9410,
    isMetroArea: true,
    affiliatedUniversity: '서강대학교',
    searchKeywords: ['서강대 한국어교육원', '서강 KLEC', 'Sogang KLEC'],
  },
  {
    name: '성균관대학교 성균어학원',
    nameEn: 'SKKU Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 종로구 성균관로 25-2',
    addressDetail: '600주년기념관',
    latitude: 37.5883,
    longitude: 126.9940,
    isMetroArea: true,
    affiliatedUniversity: '성균관대학교',
    searchKeywords: ['성균관대 어학원', 'SKKU 어학원', 'SKKU KLI'],
  },
  {
    name: '한양대학교 국제어학원',
    nameEn: 'Hanyang University International Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 성동구 왕십리로 222',
    addressDetail: '한양종합기술원',
    latitude: 37.5558,
    longitude: 127.0470,
    isMetroArea: true,
    affiliatedUniversity: '한양대학교',
    searchKeywords: ['한양대 어학원', 'Hanyang ILI'],
  },
  {
    name: '경희대학교 국제교육원',
    nameEn: 'Kyung Hee University International Education Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 동대문구 경희대로 26',
    addressDetail: '청운관',
    latitude: 37.5975,
    longitude: 127.0518,
    isMetroArea: true,
    affiliatedUniversity: '경희대학교',
    searchKeywords: ['경희대 국제교육원', 'KHU 어학당'],
  },
  {
    name: '중앙대학교 한국어교육원',
    nameEn: 'Chung-Ang University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 동작구 흑석로 84',
    addressDetail: '국제관',
    latitude: 37.5052,
    longitude: 126.9578,
    isMetroArea: true,
    affiliatedUniversity: '중앙대학교',
    searchKeywords: ['중앙대 한국어교육원', 'CAU 어학당'],
  },
  {
    name: '건국대학교 언어교육원',
    nameEn: 'Konkuk University Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 광진구 능동로 120',
    addressDetail: '새천년관',
    latitude: 37.5415,
    longitude: 127.0790,
    isMetroArea: true,
    affiliatedUniversity: '건국대학교',
    searchKeywords: ['건국대 언어교육원', 'Konkuk LI'],
  },
  {
    name: '동국대학교 한국어교육센터',
    nameEn: 'Dongguk University Korean Language Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 중구 필동로 1길 30',
    addressDetail: '명진관',
    latitude: 37.5590,
    longitude: 127.0012,
    isMetroArea: true,
    affiliatedUniversity: '동국대학교',
    searchKeywords: ['동국대 한국어센터', 'Dongguk KLC'],
  },
  {
    name: '숙명여자대학교 한국어교육센터',
    nameEn: 'Sookmyung Women\'s University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 용산구 청파로47길 100',
    addressDetail: '문신관',
    latitude: 37.5455,
    longitude: 126.9652,
    isMetroArea: true,
    affiliatedUniversity: '숙명여자대학교',
    searchKeywords: ['숙명여대 한국어센터', 'Sookmyung KLI'],
  },
  {
    name: '서울여자대학교 한국어교육원',
    nameEn: 'Seoul Women\'s University Korean Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 노원구 화랑로 621',
    addressDetail: '진리관',
    latitude: 37.6255,
    longitude: 127.0900,
    isMetroArea: true,
    affiliatedUniversity: '서울여자대학교',
    searchKeywords: ['서울여대 한국어교육원', 'SWU KLI'],
  },
  {
    name: '홍익대학교 국제언어교육원',
    nameEn: 'Hongik University International Language Institute',
    type: 'LANGUAGE_INSTITUTE',
    address: '서울특별시 마포구 와우산로 94',
    addressDetail: 'R동',
    latitude: 37.5518,
    longitude: 126.9260,
    isMetroArea: true,
    affiliatedUniversity: '홍익대학교',
    searchKeywords: ['홍익대 언어교육원', '홍대 어학당', 'Hongik ILI'],
  },

  // ===== 지방 주요 어학당 =====
  {
    name: '부산대학교 한국어교육센터',
    nameEn: 'Pusan National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '부산광역시 금정구 부산대학로 63번길 2',
    addressDetail: '국제관',
    latitude: 35.2325,
    longitude: 129.0825,
    isMetroArea: false,
    affiliatedUniversity: '부산대학교',
    searchKeywords: ['부산대 한국어센터', 'PNU KLEC'],
  },
  {
    name: '경북대학교 한국어교육센터',
    nameEn: 'Kyungpook National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '대구광역시 북구 대학로 80',
    addressDetail: '국제관',
    latitude: 35.8905,
    longitude: 128.6108,
    isMetroArea: false,
    affiliatedUniversity: '경북대학교',
    searchKeywords: ['경북대 한국어센터', 'KNU KLEC'],
  },
  {
    name: '전남대학교 한국어교육센터',
    nameEn: 'Chonnam National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '광주광역시 북구 용봉로 77',
    addressDetail: '인문대학',
    latitude: 35.1753,
    longitude: 126.9100,
    isMetroArea: false,
    affiliatedUniversity: '전남대학교',
    searchKeywords: ['전남대 한국어센터', 'CNU KLEC'],
  },
  {
    name: '충남대학교 한국어교육원',
    nameEn: 'Chungnam National University Korean Language Education Center',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 유성구 대학로 99',
    addressDetail: '인문대학',
    latitude: 36.3688,
    longitude: 127.3452,
    isMetroArea: false,
    affiliatedUniversity: '충남대학교',
    searchKeywords: ['충남대 한국어교육원', 'CNU 어학당'],
  },
  {
    name: 'KAIST 한국어학당',
    nameEn: 'KAIST Korean Language Program',
    type: 'LANGUAGE_INSTITUTE',
    address: '대전광역시 유성구 대학로 291',
    addressDetail: 'KI빌딩',
    latitude: 36.3720,
    longitude: 127.3628,
    isMetroArea: false,
    affiliatedUniversity: 'KAIST',
    searchKeywords: ['KAIST 어학당', 'KAIST KLP'],
  },
];
