// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: notification/notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "notification";

/** Enums */
export enum NotificationType {
  NOTIFICATION_TYPE_UNSPECIFIED = 0,
  APPLICATION_ALERT = 1,
  INTERVIEW_UPDATE = 2,
  REMINDER = 3,
  PROMOTION = 4,
  EMAIL_VERIFICATION = 5,
  FINANCIAL_ALERT = 6,
  STATUS_ALERT = 7,
  UNRECOGNIZED = -1,
}

export enum NotificationStatus {
  NOTIFICATION_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  SENDING = 2,
  SENT = 3,
  FAILED = 4,
  UNRECOGNIZED = -1,
}

export enum NotificationChannel {
  NOTIFICATION_CHANNEL_UNSPECIFIED = 0,
  EMAIL = 1,
  PUSH = 2,
  BOTH = 3,
  UNRECOGNIZED = -1,
}

/** Messages */
export interface Notification {
  id: string;
  userId: string;
  email?: string | undefined;
  subject?: string | undefined;
  content?: string | undefined;
  notificationType: NotificationType;
  status: NotificationStatus;
  channel: NotificationChannel;
  priority?: number | undefined;
  isRead?: boolean | undefined;
  relatedInterviewId?: string | undefined;
  relatedJobPostId?: string | undefined;
  metadata?: string | undefined;
  createdAt: string;
  readAt?: string | undefined;
  sendedAt?: string | undefined;
}

/**
 * ---------------------
 * Broadcast
 * ---------------------
 */
export interface BroadcastNotificationRequest {
  userIds: string[];
  subject?: string | undefined;
  content?: string | undefined;
  notificationType: NotificationType;
  channel: NotificationChannel;
  metadata?: string | undefined;
}

export interface BroadcastNotificationResponse {
  success: boolean;
  sent: number;
  failed: number;
  message?: string | undefined;
}

/**
 * ---------------------
 * User IDs
 * ---------------------
 */
export interface GetAllUserIdsRequest {
}

export interface GetAllUserIdsResponse {
  userIds: string[];
}

/**
 * ---------------------
 * Requests
 * ---------------------
 */
export interface SendNotificationRequest {
  userId: string;
  email?: string | undefined;
  subject?: string | undefined;
  content?: string | undefined;
  notificationType: NotificationType;
  channel: NotificationChannel;
  relatedInterviewId?: string | undefined;
  relatedJobPostId?: string | undefined;
  priority?: number | undefined;
  metadata?: string | undefined;
}

export interface GetNotificationsRequest {
  basicQuery: BasicQuery | undefined;
  userId: string;
  notificationType?: NotificationType | undefined;
}

export interface MarkAsReadRequest {
  notificationId: string;
  userId: string;
}

export interface MarkAllAsReadRequest {
  userId: string;
}

export interface GetUnreadCountRequest {
  userId: string;
}

/**
 * ---------------------
 * Responses
 * ---------------------
 */
export interface NotificationResponse {
  success: boolean;
  message?: string | undefined;
  notification?: Notification | undefined;
}

export interface NotificationsListResponse {
  data: Notification[];
  meta: PaginationMeta | undefined;
}

export interface UnreadCountResponse {
  count: number;
}

export const NOTIFICATION_PACKAGE_NAME = "notification";

/**
 * ---------------------
 * Service
 * ---------------------
 */

export interface NotificationServiceClient {
  sendNotification(request: SendNotificationRequest): Observable<NotificationResponse>;

  broadcastNotification(request: BroadcastNotificationRequest): Observable<BroadcastNotificationResponse>;

  getNotifications(request: GetNotificationsRequest): Observable<NotificationsListResponse>;

  markAsRead(request: MarkAsReadRequest): Observable<NotificationResponse>;

  markAllAsRead(request: MarkAllAsReadRequest): Observable<NotificationResponse>;

  getUnreadCount(request: GetUnreadCountRequest): Observable<UnreadCountResponse>;

  getAllUserIds(request: GetAllUserIdsRequest): Observable<GetAllUserIdsResponse>;
}

/**
 * ---------------------
 * Service
 * ---------------------
 */

export interface NotificationServiceController {
  sendNotification(
    request: SendNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  broadcastNotification(
    request: BroadcastNotificationRequest,
  ): Promise<BroadcastNotificationResponse> | Observable<BroadcastNotificationResponse> | BroadcastNotificationResponse;

  getNotifications(
    request: GetNotificationsRequest,
  ): Promise<NotificationsListResponse> | Observable<NotificationsListResponse> | NotificationsListResponse;

  markAsRead(
    request: MarkAsReadRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  markAllAsRead(
    request: MarkAllAsReadRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  getUnreadCount(
    request: GetUnreadCountRequest,
  ): Promise<UnreadCountResponse> | Observable<UnreadCountResponse> | UnreadCountResponse;

  getAllUserIds(
    request: GetAllUserIdsRequest,
  ): Promise<GetAllUserIdsResponse> | Observable<GetAllUserIdsResponse> | GetAllUserIdsResponse;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "sendNotification",
      "broadcastNotification",
      "getNotifications",
      "markAsRead",
      "markAllAsRead",
      "getUnreadCount",
      "getAllUserIds",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";
