// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/auth/member-verification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "memberVerfication";

export enum VerificationStatus {
  /** VERIFICATION_STATUS_UNSPECIFIED - Default zero value (must be first) */
  VERIFICATION_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  APPROVED = 2,
  REJECTED = 3,
  UNRECOGNIZED = -1,
}

export interface Empyt {
}

export interface SuccessResponse {
  message: string;
}

export interface MemberVerificationRequest {
  id: string;
  userId: string;
  passportPhoto: string;
  selfiePhoto: string;
  verificationStatus: VerificationStatus;
  isVerifiedBy: string;
  createAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

/** Create Requst */
export interface UpsertMemberVerificationRequest {
  userId: string;
  passportPhoto?: string | undefined;
  selfiePhoto?: string | undefined;
  verificationStatus?: VerificationStatus | undefined;
  isVerifiedby?: string | undefined;
}

/** Delete Request */
export interface DeleteMemberVerificationRequest {
  id: string;
}

export const MEMBER_VERFICATION_PACKAGE_NAME = "memberVerfication";

export interface MemberVerificationServiceClient {
  upsertVerification(request: UpsertMemberVerificationRequest): Observable<SuccessResponse>;

  deleteVerification(request: DeleteMemberVerificationRequest): Observable<SuccessResponse>;
}

export interface MemberVerificationServiceController {
  upsertVerification(
    request: UpsertMemberVerificationRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  deleteVerification(
    request: DeleteMemberVerificationRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;
}

export function MemberVerificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["upsertVerification", "deleteVerification"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MemberVerificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MemberVerificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEMBER_VERIFICATION_SERVICE_NAME = "MemberVerificationService";
