// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.5
// source: auth/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

/**
 * -----------------------------
 *  Enums
 * -----------------------------
 */
export enum UserRole {
  /** USER_ROLE_UNSPECIFIED - Required: Default zero value */
  USER_ROLE_UNSPECIFIED = 0,
  GUEST = 1,
  MEMBER = 2,
  /** INDIVIDUAL - 개인 회원 */
  INDIVIDUAL = 3,
  /** CORPORATE - 기업 회원 */
  CORPORATE = 4,
  ADMIN = 5,
  SUPERADMIN = 6,
  UNRECOGNIZED = -1,
}

export enum UserStatus {
  /** USER_STATUS_UNSPECIFIED - Required: Default zero value */
  USER_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  ACTIVE = 2,
  /** INACTIVE - Placeholder, adjust as needed */
  INACTIVE = 3,
  UNRECOGNIZED = -1,
}

export enum SocialProvider {
  NONE = 0,
  GOOGLE = 1,
  FACEBOOK = 2,
  KAKAO = 3,
  APPLE = 4,
  UNRECOGNIZED = -1,
}

/**
 * -----------------------------
 *  Core User Message
 * -----------------------------
 */
export interface User {
  id: string;
  role: UserRole;
  email?: string | undefined;
  phone?: string | undefined;
  fullName?: string | undefined;
  status: UserStatus;
  isEmailedVerified: boolean;
  isPhoneVerified: boolean;
  walletId?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

/** A generic success response used by most mutations. */
export interface RegisterSuccessResponse {
  success: boolean;
  message?: string | undefined;
}

export interface LoginSuccessResponse {
  success: boolean;
  sessionId: string;
  message: string;
}

export interface PasswordResetResponse {
  message: string;
}

export interface UserResponse {
  success: boolean;
  message?: string | undefined;
  user: User | undefined;
}

export interface SocialAuthResponse {
  success: boolean;
  message?: string | undefined;
  prvider?: string | undefined;
  picture?: string | undefined;
  user: User | undefined;
}

/** Registration request message */
export interface RegisterRequest {
  fullName: string;
  email: string;
  password: string;
  role?: string | undefined;
}

/** Login request message */
export interface LoginRequest {
  email: string;
  password: string;
}

/** Used for GetProfile. The session/auth token is expected to be passed via gRPC metadata. */
export interface GetProfileRequest {
  sessionId: string;
}

/** Used for Logout. The session/auth token is expected to be passed via gRPC metadata for invalidation. */
export interface LogoutRequest {
  sessionId: string;
}

/** Used for Reset Password. The reset token is expected to be passed via gRPC metadata. */
export interface ResetPasswordRequest {
  token: string;
  newPassword: string;
}

export interface PasswordResetRequest {
  email: string;
}

/** Used for SocialLogin. The session/auth token is expected to be passed via gRPC metadata for invalidation. */
export interface SocialLoginRequest {
  email?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  picture?: string | undefined;
  provider: SocialProvider;
  providerId: string;
}

/** Sendotp */
export interface SendOtpRequest {
  email: string;
}

/** SendOtpResponse */
export interface SendOtpResponse {
  success: boolean;
  message: string;
}

/** VerifyOtpRequest */
export interface VerifyOtpRequest {
  email: string;
  code: string;
}

/** VerifyOtpResponse */
export interface VerifyOtpResponse {
  success: boolean;
  message: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  /** Registers a new user */

  register(request: RegisterRequest): Observable<RegisterSuccessResponse>;

  /** Logs in an existing user */

  login(request: LoginRequest): Observable<LoginSuccessResponse>;

  /** Retrieves the profile of the logged-in user */

  getProfile(request: GetProfileRequest): Observable<UserResponse>;

  /** Logs out the current user */

  logout(request: LogoutRequest): Observable<RegisterSuccessResponse>;

  /** Password Reset for user */

  resetPassword(request: ResetPasswordRequest): Observable<PasswordResetResponse>;

  /** Reset Password Request for user */

  passwordReset(request: PasswordResetRequest): Observable<PasswordResetResponse>;

  /** Social Login */

  socialLogin(request: SocialLoginRequest): Observable<LoginSuccessResponse>;

  /** Send Otp mail */

  sendOtp(request: SendOtpRequest): Observable<SendOtpResponse>;

  /** Verifi Otp */

  verifyOtp(request: VerifyOtpRequest): Observable<VerifyOtpResponse>;
}

export interface AuthServiceController {
  /** Registers a new user */

  register(
    request: RegisterRequest,
  ): Promise<RegisterSuccessResponse> | Observable<RegisterSuccessResponse> | RegisterSuccessResponse;

  /** Logs in an existing user */

  login(request: LoginRequest): Promise<LoginSuccessResponse> | Observable<LoginSuccessResponse> | LoginSuccessResponse;

  /** Retrieves the profile of the logged-in user */

  getProfile(request: GetProfileRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Logs out the current user */

  logout(
    request: LogoutRequest,
  ): Promise<RegisterSuccessResponse> | Observable<RegisterSuccessResponse> | RegisterSuccessResponse;

  /** Password Reset for user */

  resetPassword(
    request: ResetPasswordRequest,
  ): Promise<PasswordResetResponse> | Observable<PasswordResetResponse> | PasswordResetResponse;

  /** Reset Password Request for user */

  passwordReset(
    request: PasswordResetRequest,
  ): Promise<PasswordResetResponse> | Observable<PasswordResetResponse> | PasswordResetResponse;

  /** Social Login */

  socialLogin(
    request: SocialLoginRequest,
  ): Promise<LoginSuccessResponse> | Observable<LoginSuccessResponse> | LoginSuccessResponse;

  /** Send Otp mail */

  sendOtp(request: SendOtpRequest): Promise<SendOtpResponse> | Observable<SendOtpResponse> | SendOtpResponse;

  /** Verifi Otp */

  verifyOtp(request: VerifyOtpRequest): Promise<VerifyOtpResponse> | Observable<VerifyOtpResponse> | VerifyOtpResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "login",
      "getProfile",
      "logout",
      "resetPassword",
      "passwordReset",
      "socialLogin",
      "sendOtp",
      "verifyOtp",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
