// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: auth/corporate-registration.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { SuccessResponse } from "../common/response";

export const protobufPackage = "corporateRegistration";

export enum VerificationStatus {
  /** VERIFICATION_STATUS_UNSPECIFIED - Default zero value (must be first) */
  VERIFICATION_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  APPROVED = 2,
  REJECTED = 3,
  UNRECOGNIZED = -1,
}

export interface CreateCorporateRegistrationRequest {
  userId: string;
  companyName: string;
  businessLicenseFile: string;
}

export interface UpdateCoporateRegistrationReqeust {
  id: string;
  companyName?: string | undefined;
  businessLicenseFile?: string | undefined;
  verificationStatus?: VerificationStatus | undefined;
  isVerifiedby?: string | undefined;
}

export interface DeleteCorporateRegistrationRequest {
  id: string;
}

export const CORPORATE_REGISTRATION_PACKAGE_NAME = "corporateRegistration";

export interface CorporateRegistrationClient {
  createCorporateRegistration(request: CreateCorporateRegistrationRequest): Observable<SuccessResponse>;

  updateCorporateRegistration(request: UpdateCoporateRegistrationReqeust): Observable<SuccessResponse>;

  deleteCorporateRegistration(request: DeleteCorporateRegistrationRequest): Observable<SuccessResponse>;
}

export interface CorporateRegistrationController {
  createCorporateRegistration(
    request: CreateCorporateRegistrationRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  updateCorporateRegistration(
    request: UpdateCoporateRegistrationReqeust,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  deleteCorporateRegistration(
    request: DeleteCorporateRegistrationRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;
}

export function CorporateRegistrationControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createCorporateRegistration",
      "updateCorporateRegistration",
      "deleteCorporateRegistration",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CorporateRegistration", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CorporateRegistration", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CORPORATE_REGISTRATION_SERVICE_NAME = "CorporateRegistration";
