// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: auth/member-verification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "memberVerfication";

/** Enums */
export enum FileType {
  FILE_TYPE_UNSPECIFIED = 0,
  PASSPORT_PHOTO = 1,
  SELFIE_PHOTO = 2,
  UNRECOGNIZED = -1,
}

export enum VerificationStatus {
  /** VERIFICATION_STATUS_UNSPECIFIED - Default zero value (must be first) */
  VERIFICATION_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  APPROVED = 2,
  REJECTED = 3,
  UNRECOGNIZED = -1,
}

/** Import standard types for an empty response and timestamp */
export interface Empyt {
}

export interface SuccessResponse {
  message: string;
}

export interface MemberVerification {
  id: string;
  userId: string;
  passportPhoto: string;
  selfiePhoto: string;
  verificationStatus: VerificationStatus;
  isVerifiedBy: string;
  createdAt: string;
  updatedAt: string;
}

/** Create Requst */
export interface UpsertMemberVerificationRequest {
  userId: string;
  passportPhoto?: string | undefined;
  selfiePhoto?: string | undefined;
}

export interface UpdatePhotoRequest {
  id: string;
  fileUrl: string;
  fileType: FileType;
}

export interface UpdateMemberVerificationRequest {
  id: string;
  passportPhoto?: string | undefined;
  selfiePhoto?: string | undefined;
  verificationStatus?: VerificationStatus | undefined;
  isVerifiedBy?: string | undefined;
}

/** Delete Request */
export interface DeleteMemberVerificationRequest {
  id: string;
}

export const MEMBER_VERFICATION_PACKAGE_NAME = "memberVerfication";

export interface MemberVerificationServiceClient {
  upsertVerification(request: UpsertMemberVerificationRequest): Observable<SuccessResponse>;

  updateMemberPhoto(request: UpdatePhotoRequest): Observable<SuccessResponse>;

  updateVerification(request: UpdateMemberVerificationRequest): Observable<SuccessResponse>;

  deleteVerification(request: DeleteMemberVerificationRequest): Observable<SuccessResponse>;
}

export interface MemberVerificationServiceController {
  upsertVerification(
    request: UpsertMemberVerificationRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  updateMemberPhoto(
    request: UpdatePhotoRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  updateVerification(
    request: UpdateMemberVerificationRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  deleteVerification(
    request: DeleteMemberVerificationRequest,
  ): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;
}

export function MemberVerificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "upsertVerification",
      "updateMemberPhoto",
      "updateVerification",
      "deleteVerification",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MemberVerificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MemberVerificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEMBER_VERIFICATION_SERVICE_NAME = "MemberVerificationService";
