// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: auth/sanction.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "sanctions";

/** Enums */
export enum SanctionType {
  SANCTION_TYPE_UNSPECIFIED = 0,
  SUSPENSION = 1,
  WARNING = 2,
  BANNED = 3,
  UNRECOGNIZED = -1,
}

/** Message */
export interface Sanction {
  id: string;
  userId: string;
  sanctionType: SanctionType;
  reason?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  createdAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface SanctionResponse {
  success: boolean;
  message?: string | undefined;
}

export interface AllSanctionsWithMetaResponse {
  data: Sanction[];
  meta: PaginationMeta | undefined;
}

export interface SingleSanctionResponse {
  message?: string | undefined;
  sanction: Sanction | undefined;
}

export interface DeleteSanctionResponse {
  success: boolean;
  message: string;
}

/**
 * ---------------------
 * CRUD Requests
 * ---------------------
 */
export interface GetAllSanctionsRequest {
  basicQuery: BasicQuery | undefined;
}

export interface GetSanctionRequest {
  sanctionId: string;
}

export interface CreateSanctionRequest {
  userId: string;
  sanctionType: SanctionType;
  reason?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
}

export interface UpdateSanctionRequest {
  sanctionId: string;
  sanctionType?: SanctionType | undefined;
  reason?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
}

export interface DeleteSanctionRequest {
  sanctionId: string;
}

export const SANCTIONS_PACKAGE_NAME = "sanctions";

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface SanctionServiceClient {
  createSanction(request: CreateSanctionRequest): Observable<SanctionResponse>;

  getSanction(request: GetSanctionRequest): Observable<SingleSanctionResponse>;

  getAllSanctions(request: GetAllSanctionsRequest): Observable<AllSanctionsWithMetaResponse>;

  updateSanction(request: UpdateSanctionRequest): Observable<SanctionResponse>;

  deleteSanction(request: DeleteSanctionRequest): Observable<DeleteSanctionResponse>;
}

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface SanctionServiceController {
  createSanction(
    request: CreateSanctionRequest,
  ): Promise<SanctionResponse> | Observable<SanctionResponse> | SanctionResponse;

  getSanction(
    request: GetSanctionRequest,
  ): Promise<SingleSanctionResponse> | Observable<SingleSanctionResponse> | SingleSanctionResponse;

  getAllSanctions(
    request: GetAllSanctionsRequest,
  ): Promise<AllSanctionsWithMetaResponse> | Observable<AllSanctionsWithMetaResponse> | AllSanctionsWithMetaResponse;

  updateSanction(
    request: UpdateSanctionRequest,
  ): Promise<SanctionResponse> | Observable<SanctionResponse> | SanctionResponse;

  deleteSanction(
    request: DeleteSanctionRequest,
  ): Promise<DeleteSanctionResponse> | Observable<DeleteSanctionResponse> | DeleteSanctionResponse;
}

export function SanctionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createSanction",
      "getSanction",
      "getAllSanctions",
      "updateSanction",
      "deleteSanction",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SanctionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SanctionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SANCTION_SERVICE_NAME = "SanctionService";
