// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: auth/user-information.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";

export const protobufPackage = "userInformation";

/** Enums */
export enum Gender {
  GENDER_UNSPECIFIED = 0,
  UNRECOGNIZED = -1,
}

/** --- User Information Message --- */
export interface UserInformation {
  id: string;
  /** Was user_id */
  userId: string;
  /** Was profile_image */
  profileImage?: string | undefined;
  gender?: string | undefined;
  address?: string | undefined;
  country?: string | undefined;
  city?:
    | string
    | undefined;
  /** Was cv_form */
  cvForm?:
    | string
    | undefined;
  /** Was additional_information */
  additionalInformation?:
    | string
    | undefined;
  /** Was created_at */
  createdAt: string;
  /** Was updated_at */
  updatedAt: string;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface UserInformationResponse {
  success: boolean;
  message?:
    | string
    | undefined;
  /** Was user_information */
  userInformation: UserInformation | undefined;
}

export interface ListUserInformationsResponse {
  /** Was user_informations */
  userInformations: UserInformation[];
  total: number;
  page: number;
  limit: number;
}

export interface DeleteUserInformationResponse {
  success: boolean;
  message: string;
}

export interface AllUserInformationsWithMetaResponse {
  data: UserInformation[];
  meta: PaginationMeta | undefined;
}

export interface GetUserInformationRequest {
  userId: string;
}

export interface ListUserInformationsRequest {
  page: number;
  limit: number;
  country?: string | undefined;
  city?: string | undefined;
}

export interface GetAllUserInformationsRequest {
  basicQuery: BasicQuery | undefined;
}

export interface CreateUserInformationRequest {
  userId: string;
  profileImage?: string | undefined;
  gender?: string | undefined;
  address?: string | undefined;
  country?: string | undefined;
  city?: string | undefined;
  cvForm?: string | undefined;
  additionalInformation?: string | undefined;
}

export interface UpdateUserInformationRequest {
  userId: string;
  profileImage?: string | undefined;
  gender?: string | undefined;
  address?: string | undefined;
  country?: string | undefined;
  city?: string | undefined;
  cvForm?: string | undefined;
  additionalInformation?: string | undefined;
}

export interface DeleteUserInformationRequest {
  userId: string;
}

export const USER_INFORMATION_PACKAGE_NAME = "userInformation";

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface UserInformationServiceClient {
  createUserInformation(request: CreateUserInformationRequest): Observable<UserInformationResponse>;

  getUserInformation(request: GetUserInformationRequest): Observable<UserInformationResponse>;

  getAllUserInformations(request: GetAllUserInformationsRequest): Observable<AllUserInformationsWithMetaResponse>;

  updateUserInformation(request: UpdateUserInformationRequest): Observable<UserInformationResponse>;

  deleteUserInformation(request: DeleteUserInformationRequest): Observable<DeleteUserInformationResponse>;

  listUserInformations(request: ListUserInformationsRequest): Observable<ListUserInformationsResponse>;
}

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface UserInformationServiceController {
  createUserInformation(
    request: CreateUserInformationRequest,
  ): Promise<UserInformationResponse> | Observable<UserInformationResponse> | UserInformationResponse;

  getUserInformation(
    request: GetUserInformationRequest,
  ): Promise<UserInformationResponse> | Observable<UserInformationResponse> | UserInformationResponse;

  getAllUserInformations(
    request: GetAllUserInformationsRequest,
  ):
    | Promise<AllUserInformationsWithMetaResponse>
    | Observable<AllUserInformationsWithMetaResponse>
    | AllUserInformationsWithMetaResponse;

  updateUserInformation(
    request: UpdateUserInformationRequest,
  ): Promise<UserInformationResponse> | Observable<UserInformationResponse> | UserInformationResponse;

  deleteUserInformation(
    request: DeleteUserInformationRequest,
  ): Promise<DeleteUserInformationResponse> | Observable<DeleteUserInformationResponse> | DeleteUserInformationResponse;

  listUserInformations(
    request: ListUserInformationsRequest,
  ): Promise<ListUserInformationsResponse> | Observable<ListUserInformationsResponse> | ListUserInformationsResponse;
}

export function UserInformationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createUserInformation",
      "getUserInformation",
      "getAllUserInformations",
      "updateUserInformation",
      "deleteUserInformation",
      "listUserInformations",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserInformationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserInformationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_INFORMATION_SERVICE_NAME = "UserInformationService";
