// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: auth/users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PaginationMeta } from "../common/basic";
import { BasicQuery } from "../common/basic-query";
import { CorporateRegistrationModel } from "./corporate-registration";
import { MemberVerification } from "./member-verification";
import { UserInformation } from "./user-information";

export const protobufPackage = "users";

/** Enums */
export enum UserRole {
  USER_ROLE_UNSPECIFIED = 0,
  GUEST = 1,
  MEMBER = 2,
  CORPORATE = 3,
  ADMIN = 4,
  SUPERADMIN = 5,
  UNRECOGNIZED = -1,
}

export enum UserStatus {
  USER_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  ACTIVE = 2,
  SUSPENDED = 3,
  REJECTED = 4,
  INACTIVE = 5,
  UNRECOGNIZED = -1,
}

/** Message */
export interface User {
  id: string;
  role: UserRole;
  email?: string | undefined;
  phone?: string | undefined;
  fullName?: string | undefined;
  status: UserStatus;
  isEmailedVerified: boolean;
  isPhoneVerified: boolean;
  walletId?: string | undefined;
  createdAt: string;
  updatedAt: string;
  userInformation?: UserInformation | undefined;
  memberIdentityVerification?: MemberVerification | undefined;
  corporateRegistration?: CorporateRegistrationModel | undefined;
}

/**
 * ---------------------
 * CRUD Responses
 * ---------------------
 */
export interface CreateUserResponse {
  success: boolean;
  message: string;
}

export interface UserResponse {
  success: boolean;
  message?: string | undefined;
  user: User | undefined;
}

export interface ListUsersResponse {
  users: User | undefined;
  total: number;
  page: number;
  limit: number;
}

export interface DeleteUserResponse {
  success: boolean;
  message: string;
}

export interface AllUsersWithMetaResponse {
  data: User[];
  meta: PaginationMeta | undefined;
}

export interface ListUsersRequest {
  page: number;
  limit: number;
  role?: UserRole | undefined;
  status?: UserStatus | undefined;
}

export interface GetUserRequest {
  userId: string;
}

export interface UpdateUserRequest {
  userId: string;
  fullName?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  password?: string | undefined;
  role?: UserRole | undefined;
  status?: UserStatus | undefined;
}

export interface DeleteUserRequest {
  userId: string;
}

export interface GetAllUsersRequest {
  basicQuery: BasicQuery | undefined;
}

export interface CreateUserRequest {
  email?: string | undefined;
  phone?: string | undefined;
  fullName?: string | undefined;
  password?: string | undefined;
  role?: UserRole | undefined;
  status?: UserStatus | undefined;
}

export const USERS_PACKAGE_NAME = "users";

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface UserServiceClient {
  createUser(request: CreateUserRequest): Observable<UserResponse>;

  getUser(request: GetUserRequest): Observable<UserResponse>;

  getAllUsers(request: GetAllUsersRequest): Observable<AllUsersWithMetaResponse>;

  updateUser(request: UpdateUserRequest): Observable<UserResponse>;

  deleteUser(request: DeleteUserRequest): Observable<DeleteUserResponse>;

  listUsers(request: ListUsersRequest): Observable<ListUsersResponse>;
}

/**
 * ---------------------
 * CRUD Service
 * ---------------------
 */

export interface UserServiceController {
  createUser(request: CreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getAllUsers(
    request: GetAllUsersRequest,
  ): Promise<AllUsersWithMetaResponse> | Observable<AllUsersWithMetaResponse> | AllUsersWithMetaResponse;

  updateUser(request: UpdateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  deleteUser(
    request: DeleteUserRequest,
  ): Promise<DeleteUserResponse> | Observable<DeleteUserResponse> | DeleteUserResponse;

  listUsers(request: ListUsersRequest): Promise<ListUsersResponse> | Observable<ListUsersResponse> | ListUsersResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "getUser", "getAllUsers", "updateUser", "deleteUser", "listUsers"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
