// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: common/basic-query.proto

/* eslint-disable */

export const protobufPackage = "common.basic.query";

/**
 * Defines the structure for basic query parameters,
 * typically used for pagination, sorting, and filtering
 * in an API request.
 */
export interface BasicQuery {
  /** page number (default: "1" */
  page?:
    | string
    | undefined;
  /** limit (default: "10") */
  limit?:
    | string
    | undefined;
  /** search keyword (default: "") */
  searchKeyword?:
    | string
    | undefined;
  /** sorting field (default: "id") */
  sortField?:
    | string
    | undefined;
  /**
   * asc or desc (default: "desc").
   * Validation for 'asc' or 'desc' must be handled by the server logic
   * after parsing the proto message.
   */
  sortType?:
    | string
    | undefined;
  /** filter model (default: "") */
  filterModel?:
    | string
    | undefined;
  /** filter keyword (default: "") */
  filterKeyword?: string | undefined;
}

export const COMMON_BASIC_QUERY_PACKAGE_NAME = "common.basic.query";
