// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: common/basic.proto

/* eslint-disable */

export const protobufPackage = "common.basic.usage";

export interface PaginationMeta {
  count: number;
  page: number;
  pageCount: number;
  limit: number;
}

export const COMMON_BASIC_USAGE_PACKAGE_NAME = "common.basic.usage";
